// RenderingServer.cs — M1 implementation of the rendering server.
//
// Depends on blinn_phong_shader_cs.Shaders (generated by sokol-shdc from
// src/Framework/Renderer/Server/shaders/blinn_phong.glsl). The compiled output
// (blinn_phong_shader.cs) lives in the same shaders/ folder and is built by
// the CompileFrameworkShaders MSBuild target in Framework.csproj.
//
// Frame loop:
//   BeginFrame()  → reset instance staging count, reset light buffer, reset stats
//   SubmitView()  → Extract ECS → Sort → Append instances (sg_append_buffer per view) → Draw groups
//   EndFrame()    → (reserved for future stats push)
// Note: sg_append_buffer (not sg_update_buffer) is required so two views in the same
//       Sokol frame can each append without clobbering one another.

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using Frent;
using Sokol;
using static Sokol.SG;
using static Sokol.Utils;
using static blinn_phong_shader_cs.Shaders;
using static pbr_shader_cs_pbr.Shaders;
using GameEditor.Framework.Core;
using GameEditor.Framework.ECS;
using GameEditor.Framework.ECS.Components;
using GameEditor.Framework.Renderer.Server.Lighting;
using GameEditor.Framework.Renderer.Server.Materials;
using GameEditor.Framework.Renderer.Server.Passes;
using GameEditor.Framework.Renderer.Server.Concurrency;
using GameEditor.Framework.Renderer.Server.Culling;
using GameEditor.Framework.Renderer.Server.Lod;
using GameEditor.Framework.Renderer.Server.Profiling;
using GameEditor.Framework.Renderer.Server.Resources;

namespace GameEditor.Framework.Renderer.Server
{
    public static unsafe class RenderingServer
    {
        private const ushort DrawFlagDisableSubMeshMaterial = 1 << 15;

        // ── Sub-systems ──────────────────────────────────────────────────────────────────

        private static readonly TextureCache       _texCache    = new();
        private static readonly MeshRegistry       _meshReg     = new();
        private static readonly MaterialRegistry   _matReg      = new(_texCache);
        private static readonly LightBuffer        _lightBuf    = new();
        private static readonly InstanceBuffer     _instanceBuf = new();
        private static readonly ShaderVariantCache _shaderCache = new();
        private static readonly ShadowAtlas        _shadowAtlas = new();
        private static readonly CubeShadowArray    _cubeShadows = new();
        private static readonly ShadowPass         _shadowPass  = new();
        private static readonly ShadowDebugPass     _shadowDebugPass = new();
        private static readonly TonemapPass         _tonemapPass = new();
        private static readonly RenderView?[]      _views       = new RenderView[RenderingConstants.MAX_VIEWS];
        private static sg_sampler _shadowSampler;
        private static sg_sampler _cubeShadowSampler;

        // ── Per-frame scratch (pre-allocated – zero hot-path allocations) ────────────────

        private static readonly DrawCommand[]  _cmds      = new DrawCommand[RenderingConstants.MAX_DRAWS];
        private static readonly InstanceData[] _cpuInst   = new InstanceData[RenderingConstants.MAX_DRAWS];
        private static int _drawCount;

        private static readonly uint[]     _sortKeys   = new uint[RenderingConstants.MAX_DRAWS];
        private static readonly int[]      _sortOrder  = new int[RenderingConstants.MAX_DRAWS];
        private static readonly DrawSorter _drawSorter = new();

        // ── M3: frustum culling ───────────────────────────────────────────────────────────
        private static readonly int[]  _visible = new int[RenderingConstants.MAX_DRAWS];

        // ── M3: per-view, per-entity LOD history ─────────────────────────────────────────────
        // Indexed by viewIndex (see SubmitView) to prevent the two editor views (Scene + Game)
        // from clobbering each other's hysteresis state. One dictionary per view.
        // Only populated for entities that carry a LodGroup component. Bounded by
        // MAX_DRAWS (16384) × MAX_VIEWS. Zero GC pressure after warm-up for a static entity set.
        // Pruned on EntityDestroyed (see ForgetEntity) to prevent unbounded growth under churn.
        private static readonly System.Collections.Generic.Dictionary<Entity, int>[] _prevLodLevel =
            InitLodHistory();

        private static System.Collections.Generic.Dictionary<Entity, int>[] InitLodHistory()
        {
            var arr = new System.Collections.Generic.Dictionary<Entity, int>[RenderingConstants.MAX_VIEWS];
            for (int i = 0; i < arr.Length; i++) arr[i] = new();
            return arr;
        }

        private static void ForgetEntity(Entity e)
        {
            foreach (var dict in _prevLodLevel) dict.Remove(e);
        }

        // Top-N light selection scratch (M2): keep the highest-importance lights only.
        private static readonly Light[] _topLights = new Light[RenderingConstants.MAX_LIGHTS];
        private static readonly float[] _topLightScores = new float[RenderingConstants.MAX_LIGHTS];
        private static int _topLightCount;

        // ── Frame stats ──────────────────────────────────────────────────────────────────

        private static FrameStats _stats;
        public static ref readonly FrameStats Stats => ref _stats;

        /// <summary>
        /// Returns the LOD index that was selected for the given entity during the last
        /// <see cref="SubmitView"/> call, or 0 if the entity has no <see cref="LodGroup"/>
        /// or has never been rendered.  Intended for read-only display in the editor
        /// Inspector — do not cache the result across frames.
        /// <paramref name="viewIndex"/> selects which view's history to read; defaults to 0,
        /// which by the editor's convention is the Scene view (see the SubmitView call sites
        /// in GameEditor-app.cs: Scene = 0, camera-preview = 1, Game = 2). Out-of-range
        /// indices return 0.
        /// </summary>
        public static int GetLastLodLevel(Entity entity, int viewIndex = 0)
        {
            if ((uint)viewIndex >= (uint)_prevLodLevel.Length) return 0;
            return _prevLodLevel[viewIndex].TryGetValue(entity, out int lv) ? lv : 0;
        }

        private static bool _initialized;
        private static bool _hasDirectionalShadow;

        // Shadow quality: 0 = 1-tap sharp, 1 = 3×3 PCF medium (default), 2 = 5×5 PCF soft.
        public static int ShadowQuality { get; set; } = 1;

        /// <summary>
        /// When true, draws a debug overlay showing one shadow atlas slice in the scene view.
        /// Toggle from code or via the editor debug toolbar.
        /// </summary>
        public static bool ShowShadowAtlasDebug { get; set; } = false;

        /// <summary>Atlas slice to visualise (0–3 directional cascades, 4–11 spot lights).</summary>
        public static int ShadowAtlasDebugSlice { get; set; } = 4;
        private static Matrix4x4 _directionalShadowViewProj;
        private static readonly Entity[] _spotShadowTopEntities = new Entity[ShadowAtlas.SpotSlices];
        private static readonly float[] _spotShadowTopScores = new float[ShadowAtlas.SpotSlices];
        private static readonly Matrix4x4[] _spotShadowViewProj = new Matrix4x4[ShadowAtlas.SpotSlices];
        private static int _spotShadowTopCount;
        private static readonly Entity[] _pointShadowTopEntities = new Entity[CubeShadowArray.MaxPointShadowLights];
        private static readonly float[] _pointShadowTopScores = new float[CubeShadowArray.MaxPointShadowLights];
        private static readonly Matrix4x4[] _pointShadowViewProj = new Matrix4x4[CubeShadowArray.MaxPointShadowLights * CubeShadowArray.FacesPerLight];
        private static int _pointShadowTopCount;

        // ── Lifecycle ────────────────────────────────────────────────────────────────────

        public static void Init()
        {
            if (_initialized) return;
            EventBus.EntityDestroyed += ForgetEntity;
            _texCache.Init();
            _shaderCache.Init();
            _shadowAtlas.Init();
            _cubeShadows.Init();
            _shadowPass.Init();
            _shadowDebugPass.Init();
            _tonemapPass.Init();
            _shadowSampler = sg_make_sampler(new sg_sampler_desc
            {
                min_filter = sg_filter.SG_FILTER_NEAREST,
                mag_filter = sg_filter.SG_FILTER_NEAREST,
                compare = sg_compare_func.SG_COMPAREFUNC_LESS_EQUAL,
                wrap_u = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                wrap_v = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                label = "shadow-atlas-sampler"
            });
            _cubeShadowSampler = sg_make_sampler(new sg_sampler_desc
            {
                min_filter = sg_filter.SG_FILTER_NEAREST,
                mag_filter = sg_filter.SG_FILTER_NEAREST,
                compare = sg_compare_func.SG_COMPAREFUNC_LESS_EQUAL,
                wrap_u = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                wrap_v = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                label = "cube-shadow-array-sampler"
            });
            _initialized = true;
        }

        public static void Shutdown()
        {
            if (!_initialized) return;
            EventBus.EntityDestroyed -= ForgetEntity;
            _initialized = false;
            _instanceBuf.Dispose();
            _matReg.Shutdown();
            _meshReg.Shutdown();
            _texCache.Shutdown();
            _shadowPass.Shutdown();
            _shadowDebugPass.Shutdown();
            _tonemapPass.Shutdown();
            _cubeShadows.Shutdown();
            _shadowAtlas.Shutdown();
            if (_shadowSampler.id != 0)
            {
                sg_destroy_sampler(_shadowSampler);
                _shadowSampler = default;
            }
            if (_cubeShadowSampler.id != 0)
            {
                sg_destroy_sampler(_cubeShadowSampler);
                _cubeShadowSampler = default;
            }
            _shaderCache.Dispose();
        }

        // ── View management ──────────────────────────────────────────────────────────────

        public static int RegisterView(RenderView view)
        {
            for (int i = 0; i < _views.Length; i++)
                if (_views[i] == null) { _views[i] = view; return i; }
            throw new InvalidOperationException("Maximum views exceeded.");
        }

        public static void UnregisterView(int viewIndex)
        {
            if ((uint)viewIndex < (uint)_views.Length) _views[viewIndex] = null;
        }

        // ── Registry accessors (for editor tooling) ───────────────────────────────────────

        public static MeshRegistry     Meshes    => _meshReg;
        public static MaterialRegistry Materials => _matReg;
        public static TextureCache     Textures  => _texCache;

        /// <summary>
        /// Imports a glTF/GLB model from the current project's Assets folder (cross-platform, via
        /// SFilesystem). Registers its meshes, PBR materials, and textures, then builds the ECS node
        /// hierarchy under a single container entity. Asynchronous (external .bin/textures are
        /// fetched first); <paramref name="onComplete"/> fires on the main thread with the container
        /// entity, or null on failure. Skinning is not yet wired — skinned models import in bind pose.
        /// </summary>
        public static void ImportGltfAsync(string assetsRelativePath, Action<Entity?>? onComplete = null)
        {
            if (!_initialized) { onComplete?.Invoke(null); return; }
            GameEditor.Framework.Renderer.Server.Assets.GltfImporter.ImportAsync(
                assetsRelativePath, _meshReg, _matReg, _texCache, ECSWorld.Instance, onComplete);
        }

        /// <summary>
        /// Re-registers a glTF/GLB's meshes, materials, and textures WITHOUT creating entities —
        /// used on scene reload to re-populate resources referenced by already-deserialized
        /// MeshRenderers (mesh keys "&lt;file&gt;#m{i}p{j}", material keys "&lt;file&gt;#mat{i}").
        /// </summary>
        public static void PreloadGltfAsync(string assetsRelativePath, Action? onComplete = null)
        {
            if (!_initialized) { onComplete?.Invoke(); return; }
            GameEditor.Framework.Renderer.Server.Assets.GltfImporter.PreloadAsync(
                assetsRelativePath, _meshReg, _matReg, _texCache, ECSWorld.Instance, onComplete);
        }

        // ── Frame loop ───────────────────────────────────────────────────────────────────

        public static void BeginFrame()
        {
            if (!_initialized) return;
            _instanceBuf.BeginFrame();
            _lightBuf.Reset();
            _stats.Reset();
            _drawCount = 0;
            FrameProfiler.BeginFrame();
        }

        public static void RenderShadowMaps(in Matrix4x4 viewProj)
        {
            if (!_initialized) return;

            FrameProfiler.Begin(FrameProfiler.Zone.ShadowPass);
            CollectLightsAndShadows(ECSWorld.Instance, in viewProj, renderShadowPasses: true);
            FrameProfiler.End(FrameProfiler.Zone.ShadowPass);
        }

        /// <summary>
        /// Applies the HDR tonemap pass using the provided HDR color image.
        /// Must be called inside an active swapchain <c>sg_begin_pass / sg_end_pass</c> block,
        /// after all geometry and post-process passes have written to the HDR render target.
        /// </summary>
        /// <param name="hdrColorView">sg_view for the RGBA16F HDR offscreen color attachment.</param>
        /// <param name="exposure">Linear exposure multiplier (default 1.0).</param>
        /// <param name="tonemapType">
        ///   0 = Linear, 1 = ACES Narkowicz, 2 = ACES Hill, 3 = KHR PBR Neutral (default 1).
        /// </param>
        public static void RenderTonemapPass(sg_view hdrColorView, float exposure = 1.0f, int tonemapType = 1)
        {
            if (!_initialized) return;
            _tonemapPass.Render(hdrColorView, exposure, tonemapType);
        }

        public static void SubmitView(
            in Matrix4x4 viewProj,
            PipelineFlags basePipelineFlags = PipelineFlags.OffscreenRt,
            int viewIndex = 0,
            bool allowShadowPassRendering = true)
        {
            if (!_initialized) return;
            var world = ECSWorld.Instance;

            // Camera position is required for light importance ranking.
            Matrix4x4.Invert(viewProj, out var invVP);
            var cameraPos = new Vector3(invVP.M41, invVP.M42, invVP.M43);

            // ── 1. Collect lights and shadow matrices ───────────────────────────────────

            CollectLightsAndShadows(world, in viewProj, allowShadowPassRendering);

            // ── 2. Extract draw commands ──────────────────────────────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.EcsExtract);
            _drawCount = 0;
            // Gate per-entity TryGetComponent<LodGroup> behind a cheap per-frame archetype check
            // so non-LOD scenes pay nothing for this feature on the hot path.
            bool anyLodGroups = world.HasAnyComponent<LodGroup>();
            // Resolve this view's LOD-history bucket ONCE, with the view-index bounds check
            // here rather than per entity in the loop. A stray viewIndex yields a null bucket,
            // so the entity simply renders without LOD history (LOD 0) instead of faulting.
            System.Collections.Generic.Dictionary<Entity, int>? lodHistory =
                anyLodGroups && (uint)viewIndex < (uint)_prevLodLevel.Length
                    ? _prevLodLevel[viewIndex]
                    : null;
            foreach (var row in world.Query<ActiveFlag, MeshRenderer, Transform>()
                                     .EnumerateWithEntities<ActiveFlag, MeshRenderer, Transform>())
            {
                if (_drawCount >= RenderingConstants.MAX_DRAWS) break;
                if (!row.Item1.Value.Active) continue;
                ref readonly var mr = ref row.Item2.Value;
                if (!mr.Visible) continue;
                ref readonly var tf = ref row.Item3.Value;

                MeshResource? meshRes = _meshReg.GetByPath(mr.MeshPath);
                if (meshRes == null) continue;

                bool disableSubMeshMaterial = string.Equals(
                    mr.MaterialPath,
                    MeshRenderer.NoMaterialSentinel,
                    StringComparison.Ordinal);

                ushort matId;
                if (string.IsNullOrEmpty(mr.MaterialPath) || disableSubMeshMaterial)
                {
                    matId = 0;
                }
                else
                {
                    matId = _matReg.GetIdByKey(mr.MaterialPath);
                    if (matId == 0)
                        matId = _matReg.GetFirstIdByMtlFile(mr.MaterialPath);
                }
                ushort drawFlags = disableSubMeshMaterial ? DrawFlagDisableSubMeshMaterial : (ushort)0;

                Matrix4x4 model    = Transform.GetWorldMatrix(world, tf);
                Aabb worldAabb      = meshRes.LocalBounds.Transform(model);
                float worldRadius   = worldAabb.Extents.Length();
                float dist          = Vector3.Distance(cameraPos, worldAabb.Center);

                // ── LOD selection ─────────────────────────────────────────────────────────
                Entity entity = row.Entity;
                LodGroup? lodGroup = null;
                int prevLod = 0;
                if (lodHistory != null)
                {
                    lodGroup = world.TryGetComponent<LodGroup>(entity, out var lgVal) ? lgVal : (LodGroup?)null;
                    lodHistory.TryGetValue(entity, out prevLod);
                }
                int lodIndex = LodSelector.Pick(worldRadius, dist, prevLod, lodGroup);
                if (lodIndex == LodSelector.Skip) { _stats.Culled++; continue; }

                // Update per-view, per-entity hysteresis state (only when entity has a LodGroup;
                // lodGroup.HasValue implies lodHistory != null — it was only set inside the guard).
                if (lodHistory != null && lodGroup.HasValue && prevLod != lodIndex)
                {
                    lodHistory[entity] = lodIndex;
                    _stats.LodSwitches++;
                }

                ushort lodMask = (ushort)(drawFlags | (ushort)(lodIndex & 0xF));
                _cmds[_drawCount]    = new DrawCommand(meshRes.Id, matId, lodMask, 0, (uint)entity.GetHashCode(), worldAabb.Center, worldRadius);
                _cpuInst[_drawCount] = new InstanceData(
                    in model,
                    new Vector4(1f, 1f, 1f, mr.ReceivesShadows ? 1f : 0f));
                _drawCount++;
            }

            FrameProfiler.End(FrameProfiler.Zone.EcsExtract);
            if (_drawCount == 0) return;

            // ── 2b. Frustum cull (parallel on non-WASM) ───────────────────────────────────

            var frustum = Frustum.ExtractFromViewProj(in viewProj);
            FrameProfiler.Begin(FrameProfiler.Zone.ParallelCull);
            ParallelCuller.Run(in frustum, _cmds, _drawCount, _visible, out int visibleCount);
            FrameProfiler.End(FrameProfiler.Zone.ParallelCull);
            _stats.TotalRenderable += _drawCount;
            _stats.Culled += _drawCount - visibleCount;
            if (visibleCount == 0) return;

            // ── 3. Sort visible commands by (MaterialId | MeshId) ─────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.Sort);
            for (int j = 0; j < visibleCount; j++)
            {
                int idx = _visible[j];
                uint noMatBit = (_cmds[idx].LodMask & DrawFlagDisableSubMeshMaterial) != 0 ? 1u : 0u;
                uint lod      = (uint)(_cmds[idx].LodMask & 0x0F);
                // Sort key (32 bits):
                //   bits 31-28: lodIndex   (4 bits  — separates LOD variants of the same mesh)
                //   bits 27-16: MaterialId (12 bits — 0-4095 IDs fit; sufficient for editor)
                //   bit  15:    noMatBit
                //   bits 14-0:  MeshId     (15 bits — 0-32767 meshes)
                // Sort-key capacity guard. `if (overflow) Debug.Fail(...)` builds the
                // interpolated message ONLY on actual overflow — Debug.Assert(cond, $"...")
                // would build it eagerly every iteration in Debug builds. Both the Debug.Fail
                // call and the now-empty branch vanish in Release ([Conditional("DEBUG")] +
                // JIT dead-code elimination of the side-effect-free test).
                if ((_cmds[idx].MaterialId & ~0xFFFu) != 0)
                    System.Diagnostics.Debug.Fail($"MaterialId {_cmds[idx].MaterialId} exceeds 12-bit sort-key capacity (max 4095).");
                if ((_cmds[idx].MeshId & ~0x7FFFu) != 0)
                    System.Diagnostics.Debug.Fail($"MeshId {_cmds[idx].MeshId} exceeds 15-bit sort-key capacity (max 32767).");
                _sortKeys[idx]  = (lod << 28)
                                | (((uint)_cmds[idx].MaterialId & 0xFFF) << 16)
                                | (noMatBit << 15)
                                | ((uint)_cmds[idx].MeshId & 0x7FFF);
                _sortOrder[j] = idx;
            }
            Array.Sort(_sortOrder, 0, visibleCount, _drawSorter);
            FrameProfiler.End(FrameProfiler.Zone.Sort);

            // ── 4. Write instance data in sorted order; ONE sg_append_buffer per view ──────

            FrameProfiler.Begin(FrameProfiler.Zone.InstanceWrite);
            _instanceBuf.ResetStaging();
            int submitCount = visibleCount;
            for (int j = 0; j < visibleCount; j++)
            {
                if (!_instanceBuf.TryAppend(in _cpuInst[_sortOrder[j]]))
                {
#if DEBUG
                    _stats.InstancesDropped += visibleCount - j;
#endif
                    submitCount = j;  // clamp: group-walking loop must not exceed staged range
                    break;
                }
            }
            if (submitCount == 0) { FrameProfiler.End(FrameProfiler.Zone.InstanceWrite); return; }
            int instanceBaseByteOffset = _instanceBuf.Flush();
            _stats.InstancesSubmitted += submitCount;
            FrameProfiler.End(FrameProfiler.Zone.InstanceWrite);

            // ── 5. Camera position from inverse VP ────────────────────────────────────────

            var vsParams = new blinn_phong_vs_params_t
            {
                view_proj  = viewProj,
                camera_pos = new Vector4(cameraPos, 1f),
                dir_shadow_vp = _hasDirectionalShadow ? _directionalShadowViewProj : Matrix4x4.Identity,
            };

            // PBR view-constant uniform blocks. Built lazily on the first PBR group so
            // scenes with no PBR materials never touch them (the light block is ~4 KB).
            bool pbrSharedBuilt = false;
            pbr_pbr_vs_params_t     pbrVs     = default;
            pbr_pbr_light_params_t  pbrLights = default;
            pbr_pbr_camera_params_t pbrCam    = default;
            pbr_pbr_ibl_params_t    pbrIbl    = default;

            // ── 6. Walk sorted groups ─────────────────────────────────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.DrawCalls);
            int instanceOffset = 0;
            int i = 0;

            while (i < submitCount)
            {
                int firstIdx = _sortOrder[i];
                ushort curMat  = _cmds[firstIdx].MaterialId;
                ushort curMesh = _cmds[firstIdx].MeshId;
                  bool disableSubMeshMaterial = (_cmds[firstIdx].LodMask & DrawFlagDisableSubMeshMaterial) != 0;
                int  curLod  = _cmds[firstIdx].LodMask & 0x0F;

                int groupSize = 0;
                while (i + groupSize < submitCount
                       && _cmds[_sortOrder[i + groupSize]].MaterialId == curMat
                      && _cmds[_sortOrder[i + groupSize]].MeshId     == curMesh
                      && ((_cmds[_sortOrder[i + groupSize]].LodMask & DrawFlagDisableSubMeshMaterial) != 0) == disableSubMeshMaterial
                      && (_cmds[_sortOrder[i + groupSize]].LodMask & 0x0F) == curLod)
                    groupSize++;

                Material?     mat  = _matReg.GetById(curMat);
                MeshResource? mesh = _meshReg.GetById(curMesh);

                // Pick the LOD mesh: lodIndex 0 = base mesh; lodIndex > 0 = LodSlots[lodIndex-1]
                if (curLod > 0 && mesh?.LodSlots is { Length: > 0 } slots)
                {
                    int slotIdx = curLod - 1;
                    if (slotIdx < slots.Length && slots[slotIdx] != null)
                        mesh = slots[slotIdx];
                    // else fall through: missing LOD slot → keep rendering base mesh
                }

                if (mesh == null || mesh.SubMeshes == null || mesh.SubMeshes.Length == 0)
                {
                    instanceOffset += groupSize;
                    i += groupSize;
                    continue;
                }

                // ── PBR path ──────────────────────────────────────────────────────────────
                // PBR materials are applied whole-group (no per-sub-mesh .mtl override).
                if (mat is PbrMaterial pbrMat)
                {
                    if (!pbrSharedBuilt)
                    {
                        BuildPbrSharedUniforms(in viewProj, cameraPos,
                            out pbrVs, out pbrLights, out pbrCam, out pbrIbl);
                        pbrSharedBuilt = true;
                    }

                    int pbrInstByteOffset = instanceBaseByteOffset
                                          + instanceOffset * Unsafe.SizeOf<InstanceData>();
                    DrawPbrGroup(pbrMat, mesh, groupSize, pbrInstByteOffset, basePipelineFlags,
                        in pbrVs, in pbrLights, in pbrCam, in pbrIbl);

                    instanceOffset += groupSize;
                    i += groupSize;
                    continue;
                }

                bool groupAlpha = mat is BlinnPhongMaterial bpmG && bpmG.HasAlpha;
                sg_apply_pipeline(_shaderCache.GetPipeline(
                    groupAlpha
                        ? basePipelineFlags | PipelineFlags.AlphaBlend
                        : basePipelineFlags));

                // Apply VS uniforms after pipeline (required by sokol validation).
                sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));

                int instByteOffset = instanceOffset * Unsafe.SizeOf<InstanceData>();

                foreach (MeshSubResource sub in mesh.SubMeshes)
                {
                    if (sub.IndexCount == 0 || sub.VertexBuffer.id == 0 || sub.IndexBuffer.id == 0)
                        continue;

                    // Per-sub-mesh material override (from .mtl material name).
                    BlinnPhongMaterial? bpm = ResolveSubMeshMaterial(mat, mesh, sub, disableSubMeshMaterial);
                    bool subAlpha = bpm?.HasAlpha ?? groupAlpha;

                    // If alpha state differs from group, re-apply pipeline then VS uniforms.
                    if (subAlpha != groupAlpha)
                    {
                        sg_apply_pipeline(_shaderCache.GetPipeline(
                            subAlpha
                                ? basePipelineFlags | PipelineFlags.AlphaBlend
                                : basePipelineFlags));
                        sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));
                    }

                    // Always apply FS uniforms per sub-mesh: each sub-mesh can have distinct
                    // Kd/Ks/Ns values from the .mtl file, independent of the group-level material.
                    BuildFsParams(bpm ?? mat, cameraPos, out var subFs);
                    sg_apply_uniforms(UB_blinn_phong_fs_params, SG_RANGE(ref subFs));

                    sg_view  diffuse  = bpm?.DiffuseMap  ?? _texCache.PlaceholderWhite;
                    sg_view  specular = bpm?.SpecularMap ?? _texCache.PlaceholderWhite;
                    sg_view  normal   = bpm?.NormalMap   ?? _texCache.PlaceholderNormal;
                    sg_view  opacity  = bpm?.OpacityMap  ?? _texCache.PlaceholderWhite;
                    sg_sampler smp    = (bpm?.Sampler.id ?? 0) != 0
                                        ? bpm!.Sampler
                                        : _texCache.DefaultSampler;

                    sg_apply_bindings(new sg_bindings
                    {
                        vertex_buffers        = { [0] = sub.VertexBuffer, [1] = _instanceBuf.Buffer },
                        vertex_buffer_offsets = { [1] = instanceBaseByteOffset + instByteOffset },
                        index_buffer          = sub.IndexBuffer,
                        views = {
                            [VIEW_diffuse_map]  = diffuse,
                            [VIEW_specular_map] = specular,
                            [VIEW_normal_map]   = normal,
                            [VIEW_opacity_map]  = opacity,
                            [VIEW_shadow_atlas] = _shadowAtlas.TextureView,
                            [VIEW_cube_shadow_array] = _cubeShadows.TextureView,
                        },
                        samplers = {
                            [SMP_diffuse_smp]  = smp,
                            [SMP_specular_smp] = smp,
                            [SMP_normal_smp]   = smp,
                            [SMP_opacity_smp]  = smp,
                            [SMP_shadow_atlas_smp] = _shadowSampler,
                            [SMP_cube_shadow_array_smp] = _cubeShadowSampler,
                        },
                    });

                    sg_draw(0u, (uint)sub.IndexCount, (uint)groupSize);
                    _stats.DrawCalls++;
                }

                instanceOffset += groupSize;
                i += groupSize;
            }
            FrameProfiler.End(FrameProfiler.Zone.DrawCalls);
        }

        public static void EndFrame() { FrameProfiler.EndFrame(); }

        /// <summary>
        /// Draws a shadow atlas debug overlay in the bottom-right corner.
        /// Must be called inside an active <c>sg_begin_pass / sg_end_pass</c>.
        /// </summary>
        public static void DrawShadowAtlasDebug(int rtWidth, int rtHeight)
        {
            if (!_initialized || !ShowShadowAtlasDebug) return;
            int size = System.Math.Min(rtWidth, rtHeight) / 4;
            int x    = rtWidth  - size - 8;
            int y    = rtHeight - size - 8;
            _shadowDebugPass.Draw(_shadowAtlas.TextureView,
                ShadowAtlasDebugSlice, x, y, size, rtWidth, rtHeight);
        }

        // ── Helpers ──────────────────────────────────────────────────────────────────────

        private static void CollectLightsAndShadows(ECSWorld world, in Matrix4x4 cameraViewProj, bool renderShadowPasses)
        {
            Matrix4x4.Invert(cameraViewProj, out var _invCamVP);
            Vector3 cameraPos = new Vector3(_invCamVP.M41, _invCamVP.M42, _invCamVP.M43);
            _lightBuf.Reset();
            _topLightCount = 0;
            _spotShadowTopCount = 0;
            _pointShadowTopCount = 0;
            _hasDirectionalShadow = false;
            _directionalShadowViewProj = Matrix4x4.Identity;
            for (int si = 0; si < _spotShadowViewProj.Length; si++)
                _spotShadowViewProj[si] = Matrix4x4.Identity;
            for (int pi = 0; pi < _pointShadowViewProj.Length; pi++)
                _pointShadowViewProj[pi] = Matrix4x4.Identity;

            Light bestDirectionalShadowLight = default;
            float bestDirectionalShadowScore = float.NegativeInfinity;
            bool hasDirectionalShadowLight = false;

            foreach (var row in world.Query<ActiveFlag, LightComponent, Transform>()
                                     .EnumerateWithEntities<ActiveFlag, LightComponent, Transform>())
            {
                if (!row.Item1.Value.Active) continue;
                ref readonly var lc = ref row.Item2.Value;
                if (!lc.Enabled) continue;
                ref readonly var lt = ref row.Item3.Value;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, lt);
                var worldPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);
                var fwd = Vector3.Normalize(new Vector3(lightWorld.M31, lightWorld.M32, lightWorld.M33));

                float importance = MathF.Max(lc.Intensity, 0f);
                if (lc.Type != GameEditor.Framework.ECS.Components.LightType.Directional)
                {
                    float distSq = Vector3.DistanceSquared(cameraPos, worldPos);
                    importance *= 1f / MathF.Max(distSq, 0.01f);
                }

                float innerRad = lc.InnerAngle * (MathF.PI / 180f);
                float outerRad = lc.OuterAngle * (MathF.PI / 180f);

                var l = new Light(
                    (Lighting.LightType)(int)lc.Type,
                    worldPos,
                    fwd,
                    lc.Color,
                    lc.Intensity,
                    lc.Range,
                    innerRad,
                    outerRad
                );
                TryInsertTopLight(in l, importance);

                if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Directional && importance > bestDirectionalShadowScore)
                {
                    bestDirectionalShadowScore = importance;
                    bestDirectionalShadowLight = l;
                    hasDirectionalShadowLight = true;
                }

                if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Spot)
                {
                    TryInsertTopSpotShadow(row.Entity, importance);
                }
                else if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Point)
                {
                    TryInsertTopPointShadow(row.Entity, importance);
                }
            }

            for (int li = 0; li < _topLightCount; li++)
            {
                if (hasDirectionalShadowLight && IsSameLight(in _topLights[li], in bestDirectionalShadowLight))
                {
                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        0);
                }
            }

            if (hasDirectionalShadowLight && TryComputeCasterBounds(world, out var casterMin, out var casterMax))
            {
                _directionalShadowViewProj = BuildDirectionalShadowViewProj(in bestDirectionalShadowLight, casterMin, casterMax);
                _hasDirectionalShadow = true;
                if (renderShadowPasses)
                    _stats.ShadowDrawCalls += _shadowPass.RenderDirectionalCounted(world, _meshReg, _shadowAtlas, 0, in _directionalShadowViewProj);
            }

            for (int si = 0; si < _spotShadowTopCount; si++)
            {
                Entity sid = _spotShadowTopEntities[si];
                if (!world.TryGetComponent<ActiveFlag>(sid, out var sa) || !sa.Active) continue;
                if (!world.TryGetComponent<LightComponent>(sid, out var slc) || slc.Type != GameEditor.Framework.ECS.Components.LightType.Spot || !slc.CastsShadows) continue;
                if (!world.TryGetComponent<Transform>(sid, out var slt)) continue;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, slt);
                var spotPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);
                var spotFwd = Vector3.Normalize(new Vector3(lightWorld.M31, lightWorld.M32, lightWorld.M33));
                float outerRad = slc.OuterAngle * (MathF.PI / 180f);

                Matrix4x4 spotVp = BuildSpotShadowViewProj(spotPos, spotFwd, slc.Range, outerRad);
                int atlasSlice = ShadowAtlas.DirectionalCascades + si;
                if (renderShadowPasses)
                    _stats.ShadowDrawCalls += _shadowPass.RenderSpotCounted(world, _meshReg, _shadowAtlas, atlasSlice, in spotVp);
                _spotShadowViewProj[si] = spotVp;

                for (int li = 0; li < _topLightCount; li++)
                {
                    if (_topLights[li].Type != Lighting.LightType.Spot) continue;
                    if (Vector3.DistanceSquared(_topLights[li].Position, spotPos) > 0.0001f) continue;

                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        atlasSlice);
                    break;
                }
            }

            for (int pi = 0; pi < _pointShadowTopCount; pi++)
            {
                Entity pid = _pointShadowTopEntities[pi];
                if (!world.TryGetComponent<ActiveFlag>(pid, out var pa) || !pa.Active) continue;
                if (!world.TryGetComponent<LightComponent>(pid, out var plc) || plc.Type != GameEditor.Framework.ECS.Components.LightType.Point || !plc.CastsShadows) continue;
                if (!world.TryGetComponent<Transform>(pid, out var plt)) continue;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, plt);
                var pointPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);

                for (int face = 0; face < CubeShadowArray.FacesPerLight; face++)
                {
                    Matrix4x4 pointFaceVp = BuildPointShadowFaceViewProj(pointPos, face, plc.Range);
                    if (renderShadowPasses)
                        _stats.ShadowDrawCalls += _shadowPass.RenderPointFaceCounted(world, _meshReg, _cubeShadows, pi, face, in pointFaceVp);
                    _pointShadowViewProj[pi * CubeShadowArray.FacesPerLight + face] = pointFaceVp;
                }

                for (int li = 0; li < _topLightCount; li++)
                {
                    if (_topLights[li].Type != Lighting.LightType.Point) continue;
                    if (Vector3.DistanceSquared(_topLights[li].Position, pointPos) > 0.0001f) continue;

                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        pi);
                    break;
                }
            }

            _lightBuf.Reset();
            for (int li = 0; li < _topLightCount; li++)
            {
                _lightBuf.Add(in _topLights[li]);
            }
        }

        private static void BuildFsParams(Material? mat, Vector3 cameraPos,
                                          out blinn_phong_fs_params_t fs)
        {
            fs = new blinn_phong_fs_params_t();

            if (mat is BlinnPhongMaterial bpm)
            {
                fs.material_kd_alpha = new Vector4(bpm.DiffuseColor,  bpm.Opacity);
                fs.material_ks_shin  = new Vector4(bpm.SpecularColor, bpm.Shininess);
            }
            else
            {
                fs.material_kd_alpha = Vector4.One;
                fs.material_ks_shin  = new Vector4(0f, 0f, 0f, 1f);
            }

            fs.ambient_num = new Vector4(0.1f, 0.1f, 0.1f, _lightBuf.Count);
            fs.cam_pos_pad = new Vector4(cameraPos, (float)ShadowQuality);

            int n      = _lightBuf.Count;
            var lights = _lightBuf.ActiveSpan;
            for (int l = 0; l < n; l++)
            {
                int b = l * 4;
                fs.lights_data[b + 0] = lights[l].PositionType;
                fs.lights_data[b + 1] = lights[l].DirectionRange;
                fs.lights_data[b + 2] = lights[l].ColorIntensity;
                fs.lights_data[b + 3] = lights[l].SpotShadow;
            }

            for (int si = 0; si < ShadowAtlas.SpotSlices; si++)
            {
                int b = si * 4;
                var m = _spotShadowViewProj[si];
                fs.spot_shadow_vp[b + 0] = new Vector4(m.M11, m.M12, m.M13, m.M14);
                fs.spot_shadow_vp[b + 1] = new Vector4(m.M21, m.M22, m.M23, m.M24);
                fs.spot_shadow_vp[b + 2] = new Vector4(m.M31, m.M32, m.M33, m.M34);
                fs.spot_shadow_vp[b + 3] = new Vector4(m.M41, m.M42, m.M43, m.M44);
            }

            for (int pi = 0; pi < _pointShadowViewProj.Length; pi++)
            {
                int b = pi * 4;
                var m = _pointShadowViewProj[pi];
                fs.point_shadow_vp[b + 0] = new Vector4(m.M11, m.M12, m.M13, m.M14);
                fs.point_shadow_vp[b + 1] = new Vector4(m.M21, m.M22, m.M23, m.M24);
                fs.point_shadow_vp[b + 2] = new Vector4(m.M31, m.M32, m.M33, m.M34);
                fs.point_shadow_vp[b + 3] = new Vector4(m.M41, m.M42, m.M43, m.M44);
            }
        }

        // ── PBR forward path ───────────────────────────────────────────────────────────

        /// <summary>
        /// Builds the four view-constant PBR uniform blocks (vertex params, packed light block,
        /// camera, IBL). Called once per <see cref="SubmitView"/> on the first PBR group.
        /// The light block reuses the same packed GpuLight[32] format as <see cref="BuildFsParams"/>.
        /// </summary>
        private static void BuildPbrSharedUniforms(
            in Matrix4x4 viewProj, Vector3 cameraPos,
            out pbr_pbr_vs_params_t vs,
            out pbr_pbr_light_params_t lights,
            out pbr_pbr_camera_params_t cam,
            out pbr_pbr_ibl_params_t ibl)
        {
            vs = new pbr_pbr_vs_params_t
            {
                view_proj            = viewProj,
                eye_pos              = cameraPos,
                use_uniform_skinning = 1,   // unused by the base variant; reserved for skinning
            };

            lights = new pbr_pbr_light_params_t();
            int n = _lightBuf.Count;
            var span = _lightBuf.ActiveSpan;
            for (int l = 0; l < n; l++)
            {
                int b = l * 4;
                lights.lights_data[b + 0] = span[l].PositionType;
                lights.lights_data[b + 1] = span[l].DirectionRange;
                lights.lights_data[b + 2] = span[l].ColorIntensity;
                lights.lights_data[b + 3] = span[l].SpotShadow;
            }
            // Base variant reads only ambient_num.w (= light count); ambient colour comes
            // from pbr_rendering_flags.ambient_strength. spot/point shadow VPs stay zeroed
            // (the base variant samples no punctual shadows — that is a later increment).
            lights.ambient_num = new Vector4(0f, 0f, 0f, n);

            cam = new pbr_pbr_camera_params_t { u_Camera = cameraPos };

            // IBL is disabled in this increment (use_ibl=0). The block must still be valid
            // because ibl.glsl statically references these fields.
            ibl = new pbr_pbr_ibl_params_t
            {
                u_EnvIntensity      = 1f,
                u_EnvBlurNormalized = 0f,
                u_MipCount          = 1,
                u_EnvRotation       = Matrix4x4.Identity,
                u_ViewMatrix        = Matrix4x4.Identity,
                u_ProjectionMatrix  = Matrix4x4.Identity,
                u_ModelMatrix       = Matrix4x4.Identity,
            };
        }

        /// <summary>
        /// Draws one instanced group of a single <see cref="PbrMaterial"/> through the base
        /// PBR variant. Unset texture slots fall back to placeholders; the IBL env slots bind
        /// the placeholder cube (never sampled while use_ibl=0).
        /// </summary>
        private static void DrawPbrGroup(
            PbrMaterial mat, MeshResource mesh, int groupSize, int instanceByteOffset,
            PipelineFlags basePipelineFlags,
            in pbr_pbr_vs_params_t vs,
            in pbr_pbr_light_params_t lights,
            in pbr_pbr_camera_params_t cam,
            in pbr_pbr_ibl_params_t ibl)
        {
            bool blend = mat.AlphaMode == 2;
            PipelineFlags pf = basePipelineFlags;
            if (mat.DoubleSided) pf |= PipelineFlags.DoubleSided;
            if (blend)           pf |= PipelineFlags.AlphaBlend;
            sg_apply_pipeline(_shaderCache.GetPbrPipeline(pf));

            var matParams = new pbr_pbr_material_params_t
            {
                base_color_factor          = mat.BaseColorFactor,
                emissive_factor            = mat.EmissiveFactor,
                metallic_factor            = mat.MetallicFactor,
                roughness_factor           = mat.RoughnessFactor,
                has_base_color_tex         = mat.BaseColorMap.id         != 0 ? 1f : 0f,
                has_metallic_roughness_tex = mat.MetallicRoughnessMap.id != 0 ? 1f : 0f,
                has_normal_tex             = mat.NormalMap.id            != 0 ? 1f : 0f,
                has_occlusion_tex          = mat.OcclusionMap.id         != 0 ? 1f : 0f,
                has_emissive_tex           = mat.EmissiveMap.id          != 0 ? 1f : 0f,
                alpha_cutoff               = mat.AlphaCutoff,
                emissive_strength          = mat.EmissiveStrength,
                occlusion_strength         = mat.OcclusionStrength,
                ior                        = 1.5f,
                normal_map_scale           = mat.NormalMapScale,
                // Base UV path uses texcoord set 0 with identity texture transforms.
                base_color_tex_scale         = Vector2.One,
                metallic_roughness_tex_scale = Vector2.One,
                normal_tex_scale             = Vector2.One,
                occlusion_tex_scale          = Vector2.One,
                emissive_tex_scale           = Vector2.One,
            };

            var flags = new pbr_pbr_rendering_flags_t
            {
                use_ibl             = 0,
                use_punctual_lights = 1,
                alphamode           = mat.AlphaMode,
                linear_output       = 0,      // LDR RGBA8 target → tonemap + sRGB in-shader
                ambient_strength    = 0.25f,
            };

            sg_apply_uniforms(UB_pbr_pbr_vs_params,       SG_RANGE(ref Unsafe.AsRef(in vs)));
            sg_apply_uniforms(UB_pbr_pbr_material_params, SG_RANGE(ref matParams));
            sg_apply_uniforms(UB_pbr_pbr_light_params,    SG_RANGE(ref Unsafe.AsRef(in lights)));
            sg_apply_uniforms(UB_pbr_pbr_ibl_params,      SG_RANGE(ref Unsafe.AsRef(in ibl)));
            sg_apply_uniforms(UB_pbr_pbr_camera_params,   SG_RANGE(ref Unsafe.AsRef(in cam)));
            sg_apply_uniforms(UB_pbr_pbr_rendering_flags, SG_RANGE(ref flags));

            sg_view baseColor = mat.BaseColorMap.id         != 0 ? mat.BaseColorMap         : _texCache.PlaceholderWhite;
            sg_view metalRgh  = mat.MetallicRoughnessMap.id != 0 ? mat.MetallicRoughnessMap : _texCache.PlaceholderWhite;
            sg_view normalMap = mat.NormalMap.id            != 0 ? mat.NormalMap            : _texCache.PlaceholderNormal;
            sg_view occlusion = mat.OcclusionMap.id         != 0 ? mat.OcclusionMap         : _texCache.PlaceholderWhite;
            sg_view emissive  = mat.EmissiveMap.id          != 0 ? mat.EmissiveMap          : _texCache.PlaceholderBlack;
            sg_view cube      = _texCache.PlaceholderCube;
            sg_view lut       = _texCache.PlaceholderWhite;
            sg_sampler matSmp = mat.Sampler.id != 0 ? mat.Sampler : _texCache.DefaultSampler;
            sg_sampler iblSmp = _texCache.DefaultSampler;

            foreach (MeshSubResource sub in mesh.SubMeshes)
            {
                if (sub.IndexCount == 0 || sub.VertexBuffer.id == 0 || sub.IndexBuffer.id == 0)
                    continue;

                sg_apply_bindings(new sg_bindings
                {
                    vertex_buffers        = { [0] = sub.VertexBuffer, [1] = _instanceBuf.Buffer },
                    vertex_buffer_offsets = { [1] = instanceByteOffset },
                    index_buffer          = sub.IndexBuffer,
                    views = {
                        [VIEW_pbr_u_BaseColorTexture]         = baseColor,
                        [VIEW_pbr_u_MetallicRoughnessTexture] = metalRgh,
                        [VIEW_pbr_u_NormalTexture]            = normalMap,
                        [VIEW_pbr_u_OcclusionTexture]         = occlusion,
                        [VIEW_pbr_u_EmissiveTexture]          = emissive,
                        [VIEW_pbr_u_GGXEnvTexture]            = cube,
                        [VIEW_pbr_u_LambertianEnvTexture]     = cube,
                        [VIEW_pbr_u_GGXLUTTexture]            = lut,
                    },
                    samplers = {
                        [SMP_pbr_u_BaseColorSampler]         = matSmp,
                        [SMP_pbr_u_MetallicRoughnessSampler] = matSmp,
                        [SMP_pbr_u_NormalSampler]            = matSmp,
                        [SMP_pbr_u_OcclusionSampler]         = matSmp,
                        [SMP_pbr_u_EmissiveSampler]          = matSmp,
                        [SMP_pbr_u_GGXEnvSampler_Raw]        = iblSmp,
                        [SMP_pbr_u_LambertianEnvSampler_Raw] = iblSmp,
                        [SMP_pbr_u_GGXLUTSampler_Raw]        = iblSmp,
                    },
                });

                sg_draw(0u, (uint)sub.IndexCount, (uint)groupSize);
                _stats.DrawCalls++;
            }
        }

        private static BlinnPhongMaterial? ResolveSubMeshMaterial(
            Material? entityMat, MeshResource mesh, MeshSubResource sub, bool disableSubMeshMaterial)
        {
            if (!disableSubMeshMaterial
                && sub.MaterialKey.Length > 0
                && _matReg.GetByKey(sub.MaterialKey) is BlinnPhongMaterial subBpm)
                return subBpm;
            return entityMat as BlinnPhongMaterial;
        }

        private static Matrix4x4 BuildDirectionalShadowViewProj(in Light light, Vector3 casterMin, Vector3 casterMax)
        {
            const float DepthExtension = 50f; // extra depth behind casters so receivers (e.g. the floor) stay in range
            const float Pad            = 2f;  // world-space margin so grazing-angle shadows aren't clipped

            Vector3 toLight = Vector3.Normalize(-light.Direction);
            Vector3 up = Vector3.UnitY;
            if (MathF.Abs(Vector3.Dot(up, toLight)) > 0.98f)
                up = Vector3.UnitZ;

            // Fit the ortho frustum tightly to the shadow-casting geometry rather than the
            // camera frustum. The camera frustum can be 100+ units across, which wastes
            // almost the entire 2048² atlas slice on empty space and leaves the actual
            // casters only a few dozen texels (pixelated shadows that PCF then smears).
            // A bounding *sphere* keeps the box size constant as casters rotate, so the
            // texel-snap below can remove shadow-edge crawl. This is also inherently
            // camera-independent, so shadows never vanish as the camera pulls away.
            Vector3 center = (casterMin + casterMax) * 0.5f;
            float radius   = MathF.Max((casterMax - casterMin).Length() * 0.5f, 0.1f);
            float boxHalf  = radius + Pad;

            Vector3 lightEye = center + toLight * (radius + DepthExtension);
            Matrix4x4 lightView = Matrix4x4.CreateLookAt(lightEye, center, up);

            Vector3 centerLS = Vector3.Transform(center, lightView);

            float minX = centerLS.X - boxHalf;
            float minY = centerLS.Y - boxHalf;

            // Texel-snap the box origin in light space so edges don't crawl when casters move.
            float worldPerTexel = (2f * boxHalf) / ShadowAtlas.SliceSize;
            minX = MathF.Floor(minX / worldPerTexel) * worldPerTexel;
            minY = MathF.Floor(minY / worldPerTexel) * worldPerTexel;
            float maxX = minX + 2f * boxHalf;
            float maxY = minY + 2f * boxHalf;

            // Right-handed light view: casters lie in front of the eye at negative Z.
            float centerDepth = -centerLS.Z;
            float near = MathF.Max(0.05f, centerDepth - radius - Pad);
            float far  = centerDepth + radius + DepthExtension;

            Matrix4x4 proj = Matrix4x4.CreateOrthographicOffCenter(minX, maxX, minY, maxY, near, far);
            return lightView * proj;
        }

        /// <summary>
        /// World-space AABB of all active, visible, shadow-casting meshes.
        /// Returns false when the scene has no casters (directional shadows are then skipped).
        /// </summary>
        private static bool TryComputeCasterBounds(ECSWorld world, out Vector3 min, out Vector3 max)
        {
            min = new Vector3(float.MaxValue);
            max = new Vector3(float.MinValue);
            bool any = false;

            foreach (var row in world.Query<ActiveFlag, MeshRenderer, Transform>()
                                     .Enumerate<ActiveFlag, MeshRenderer, Transform>())
            {
                if (!row.Item1.Value.Active) continue;
                ref readonly var mr = ref row.Item2.Value;
                if (!mr.Visible || !mr.CastsShadows) continue;
                ref readonly var tf = ref row.Item3.Value;

                MeshResource? mesh = _meshReg.GetByPath(mr.MeshPath);
                if (mesh == null) continue;

                Aabb worldBounds = mesh.LocalBounds.Transform(Transform.GetWorldMatrix(world, tf));
                min = Vector3.Min(min, worldBounds.Min);
                max = Vector3.Max(max, worldBounds.Max);
                any = true;
            }

            return any;
        }

        private static Matrix4x4 BuildSpotShadowViewProj(Vector3 position, Vector3 direction, float range, float outerAngleRad)
        {
            Vector3 target = position + direction;
            Vector3 up = Vector3.UnitY;
            if (MathF.Abs(Vector3.Dot(up, direction)) > 0.98f)
                up = Vector3.UnitZ;

            float fov = MathF.Max(outerAngleRad * 2f, 0.1f);
            float farPlane  = MathF.Max(range, 0.1f);
            // Perspective shadow depth is highly non-linear: a tiny near plane pushes
            // nearly the whole [0,1] depth range into the first few percent of distance,
            // which inflates the effective world-space depth bias near the far plane and
            // makes short occluders (e.g. a cube on the floor) stop casting shadows.
            // Keep the near plane as large as the range allows to preserve precision.
            // (Orthographic directional shadows have linear depth and don't need this.)
            float nearPlane = MathF.Max(0.5f, farPlane * 0.1f);
            Matrix4x4 view = Matrix4x4.CreateLookAt(position, target, up);
            Matrix4x4 proj = Matrix4x4.CreatePerspectiveFieldOfView(fov, 1f, nearPlane, farPlane);
            return view * proj;
        }

        private static Matrix4x4 BuildPointShadowFaceViewProj(Vector3 position, int faceIndex, float range)
        {
            Vector3 dir;
            Vector3 up;
            switch (faceIndex)
            {
                case 0: dir = Vector3.UnitX; up = -Vector3.UnitY; break;
                case 1: dir = -Vector3.UnitX; up = -Vector3.UnitY; break;
                case 2: dir = Vector3.UnitY; up = Vector3.UnitZ; break;
                case 3: dir = -Vector3.UnitY; up = -Vector3.UnitZ; break;
                case 4: dir = Vector3.UnitZ; up = -Vector3.UnitY; break;
                default: dir = -Vector3.UnitZ; up = -Vector3.UnitY; break;
            }

            // See BuildSpotShadowViewProj: a larger near plane preserves perspective
            // depth precision so the constant shader bias stays small in world space.
            float farPlane  = MathF.Max(range, 0.1f);
            float nearPlane = MathF.Max(0.5f, farPlane * 0.1f);
            Matrix4x4 view = Matrix4x4.CreateLookAt(position, position + dir, up);
            Matrix4x4 proj = Matrix4x4.CreatePerspectiveFieldOfView(MathF.PI * 0.5f, 1f, nearPlane, farPlane);
            return view * proj;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopLight(in Light light, float score)
        {
            if (_topLightCount < RenderingConstants.MAX_LIGHTS)
            {
                int insert = _topLightCount;
                while (insert > 0 && score > _topLightScores[insert - 1]) insert--;
                for (int i = _topLightCount; i > insert; i--)
                {
                    _topLights[i] = _topLights[i - 1];
                    _topLightScores[i] = _topLightScores[i - 1];
                }
                _topLights[insert] = light;
                _topLightScores[insert] = score;
                _topLightCount++;
                return;
            }

            // Already full: drop low-priority light immediately.
            if (score <= _topLightScores[RenderingConstants.MAX_LIGHTS - 1]) return;

            int at = RenderingConstants.MAX_LIGHTS - 1;
            while (at > 0 && score > _topLightScores[at - 1]) at--;
            for (int i = RenderingConstants.MAX_LIGHTS - 1; i > at; i--)
            {
                _topLights[i] = _topLights[i - 1];
                _topLightScores[i] = _topLightScores[i - 1];
            }
            _topLights[at] = light;
            _topLightScores[at] = score;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool IsSameLight(in Light a, in Light b)
        {
            return a.Type == b.Type
                && a.Position == b.Position
                && a.Direction == b.Direction
                && a.Color == b.Color
                && a.Intensity == b.Intensity
                && a.Range == b.Range
                && a.InnerAngle == b.InnerAngle
                && a.OuterAngle == b.OuterAngle;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopSpotShadow(Entity entity, float score)
        {
            if (_spotShadowTopCount < ShadowAtlas.SpotSlices)
            {
                int insert = _spotShadowTopCount;
                while (insert > 0 && score > _spotShadowTopScores[insert - 1])
                {
                    _spotShadowTopEntities[insert] = _spotShadowTopEntities[insert - 1];
                    _spotShadowTopScores[insert] = _spotShadowTopScores[insert - 1];
                    insert--;
                }
                _spotShadowTopEntities[insert] = entity;
                _spotShadowTopScores[insert] = score;
                _spotShadowTopCount++;
                return;
            }

            if (score <= _spotShadowTopScores[ShadowAtlas.SpotSlices - 1]) return;

            int at = ShadowAtlas.SpotSlices - 1;
            while (at > 0 && score > _spotShadowTopScores[at - 1])
            {
                _spotShadowTopEntities[at] = _spotShadowTopEntities[at - 1];
                _spotShadowTopScores[at] = _spotShadowTopScores[at - 1];
                at--;
            }
            _spotShadowTopEntities[at] = entity;
            _spotShadowTopScores[at] = score;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopPointShadow(Entity entity, float score)
        {
            if (_pointShadowTopCount < CubeShadowArray.MaxPointShadowLights)
            {
                int insert = _pointShadowTopCount;
                while (insert > 0 && score > _pointShadowTopScores[insert - 1])
                {
                    _pointShadowTopEntities[insert] = _pointShadowTopEntities[insert - 1];
                    _pointShadowTopScores[insert] = _pointShadowTopScores[insert - 1];
                    insert--;
                }
                _pointShadowTopEntities[insert] = entity;
                _pointShadowTopScores[insert] = score;
                _pointShadowTopCount++;
                return;
            }

            if (score <= _pointShadowTopScores[CubeShadowArray.MaxPointShadowLights - 1]) return;

            int at = CubeShadowArray.MaxPointShadowLights - 1;
            while (at > 0 && score > _pointShadowTopScores[at - 1])
            {
                _pointShadowTopEntities[at] = _pointShadowTopEntities[at - 1];
                _pointShadowTopScores[at] = _pointShadowTopScores[at - 1];
                at--;
            }
            _pointShadowTopEntities[at] = entity;
            _pointShadowTopScores[at] = score;
        }

        private sealed class DrawSorter : System.Collections.Generic.IComparer<int>
        {
            public int Compare(int x, int y) => _sortKeys[x].CompareTo(_sortKeys[y]);
        }
    }
}
