// RenderingServer.cs — M1 implementation of the rendering server.
//
// Depends on blinn_phong_shader_cs.Shaders (generated by sokol-shdc from
// src/Framework/Renderer/Server/shaders/blinn_phong.glsl). The compiled output
// (blinn_phong_shader.cs) lives in the same shaders/ folder and is built by
// the CompileFrameworkShaders MSBuild target in Framework.csproj.
//
// Frame loop:
//   BeginFrame()  → reset instance staging count, reset light buffer, reset stats
//   SubmitView()  → Extract ECS → Sort → Append instances (sg_append_buffer per view) → Draw groups
//   EndFrame()    → (reserved for future stats push)
// Note: sg_append_buffer (not sg_update_buffer) is required so two views in the same
//       Sokol frame can each append without clobbering one another.

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using Frent;
using Sokol;
using static Sokol.SG;
using static Sokol.Utils;
using static blinn_phong_shader_cs.Shaders;
using GameEditor.Framework.Core;
using GameEditor.Framework.ECS;
using GameEditor.Framework.ECS.Components;
using GameEditor.Framework.Renderer.Server.Lighting;
using GameEditor.Framework.Renderer.Server.Materials;
using GameEditor.Framework.Renderer.Server.Passes;
using GameEditor.Framework.Renderer.Server.Concurrency;
using GameEditor.Framework.Renderer.Server.Culling;
using GameEditor.Framework.Renderer.Server.Lod;
using GameEditor.Framework.Renderer.Server.Profiling;
using GameEditor.Framework.Renderer.Server.Resources;

namespace GameEditor.Framework.Renderer.Server
{
    public static unsafe class RenderingServer
    {
        private const ushort DrawFlagDisableSubMeshMaterial = 1 << 15;

        // ── Sub-systems ──────────────────────────────────────────────────────────────────

        private static readonly TextureCache       _texCache    = new();
        private static readonly MeshRegistry       _meshReg     = new();
        private static readonly MaterialRegistry   _matReg      = new(_texCache);
        private static readonly LightBuffer        _lightBuf    = new();
        private static readonly InstanceBuffer     _instanceBuf = new();
        private static readonly ShaderVariantCache _shaderCache = new();
        private static readonly ShadowAtlas        _shadowAtlas = new();
        private static readonly CubeShadowArray    _cubeShadows = new();
        private static readonly ShadowPass         _shadowPass  = new();
        private static readonly ShadowDebugPass     _shadowDebugPass = new();
        private static readonly RenderView?[]      _views       = new RenderView[RenderingConstants.MAX_VIEWS];
        private static sg_sampler _shadowSampler;
        private static sg_sampler _cubeShadowSampler;

        // ── Per-frame scratch (pre-allocated – zero hot-path allocations) ────────────────

        private static readonly DrawCommand[]  _cmds      = new DrawCommand[RenderingConstants.MAX_DRAWS];
        private static readonly InstanceData[] _cpuInst   = new InstanceData[RenderingConstants.MAX_DRAWS];
        private static int _drawCount;

        private static readonly uint[]     _sortKeys   = new uint[RenderingConstants.MAX_DRAWS];
        private static readonly int[]      _sortOrder  = new int[RenderingConstants.MAX_DRAWS];
        private static readonly DrawSorter _drawSorter = new();

        // ── M3: frustum culling ───────────────────────────────────────────────────────────
        private static readonly int[]  _visible = new int[RenderingConstants.MAX_DRAWS];

        // Top-N light selection scratch (M2): keep the highest-importance lights only.
        private static readonly Light[] _topLights = new Light[RenderingConstants.MAX_LIGHTS];
        private static readonly float[] _topLightScores = new float[RenderingConstants.MAX_LIGHTS];
        private static int _topLightCount;

        // ── Frame stats ──────────────────────────────────────────────────────────────────

        private static FrameStats _stats;
        public static ref readonly FrameStats Stats => ref _stats;

        private static bool _initialized;
        private static bool _hasDirectionalShadow;

        // Shadow quality: 0 = 1-tap sharp, 1 = 3×3 PCF medium (default), 2 = 5×5 PCF soft.
        public static int ShadowQuality { get; set; } = 1;

        /// <summary>
        /// When true, draws a debug overlay showing one shadow atlas slice in the scene view.
        /// Toggle from code or via the editor debug toolbar.
        /// </summary>
        public static bool ShowShadowAtlasDebug { get; set; } = false;

        /// <summary>Atlas slice to visualise (0–3 directional cascades, 4–11 spot lights).</summary>
        public static int ShadowAtlasDebugSlice { get; set; } = 4;
        private static Matrix4x4 _directionalShadowViewProj;
        private static readonly int[] _spotShadowTopIndices = new int[ShadowAtlas.SpotSlices];
        private static readonly float[] _spotShadowTopScores = new float[ShadowAtlas.SpotSlices];
        private static readonly Matrix4x4[] _spotShadowViewProj = new Matrix4x4[ShadowAtlas.SpotSlices];
        private static int _spotShadowTopCount;
        private static readonly int[] _pointShadowTopIndices = new int[CubeShadowArray.MaxPointShadowLights];
        private static readonly float[] _pointShadowTopScores = new float[CubeShadowArray.MaxPointShadowLights];
        private static readonly Matrix4x4[] _pointShadowViewProj = new Matrix4x4[CubeShadowArray.MaxPointShadowLights * CubeShadowArray.FacesPerLight];
        private static int _pointShadowTopCount;

        // ── Lifecycle ────────────────────────────────────────────────────────────────────

        public static void Init()
        {
            if (_initialized) return;
            _texCache.Init();
            _shaderCache.Init();
            _shadowAtlas.Init();
            _cubeShadows.Init();
            _shadowPass.Init();
            _shadowDebugPass.Init();
            _shadowSampler = sg_make_sampler(new sg_sampler_desc
            {
                min_filter = sg_filter.SG_FILTER_NEAREST,
                mag_filter = sg_filter.SG_FILTER_NEAREST,
                compare = sg_compare_func.SG_COMPAREFUNC_LESS_EQUAL,
                wrap_u = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                wrap_v = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                label = "shadow-atlas-sampler"
            });
            _cubeShadowSampler = sg_make_sampler(new sg_sampler_desc
            {
                min_filter = sg_filter.SG_FILTER_NEAREST,
                mag_filter = sg_filter.SG_FILTER_NEAREST,
                compare = sg_compare_func.SG_COMPAREFUNC_LESS_EQUAL,
                wrap_u = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                wrap_v = sg_wrap.SG_WRAP_CLAMP_TO_EDGE,
                label = "cube-shadow-array-sampler"
            });
            _initialized = true;
        }

        public static void Shutdown()
        {
            if (!_initialized) return;
            _initialized = false;
            _instanceBuf.Dispose();
            _matReg.Shutdown();
            _meshReg.Shutdown();
            _texCache.Shutdown();
            _shadowPass.Shutdown();
            _shadowDebugPass.Shutdown();
            _cubeShadows.Shutdown();
            _shadowAtlas.Shutdown();
            if (_shadowSampler.id != 0)
            {
                sg_destroy_sampler(_shadowSampler);
                _shadowSampler = default;
            }
            if (_cubeShadowSampler.id != 0)
            {
                sg_destroy_sampler(_cubeShadowSampler);
                _cubeShadowSampler = default;
            }
            _shaderCache.Dispose();
        }

        // ── View management ──────────────────────────────────────────────────────────────

        public static int RegisterView(RenderView view)
        {
            for (int i = 0; i < _views.Length; i++)
                if (_views[i] == null) { _views[i] = view; return i; }
            throw new InvalidOperationException("Maximum views exceeded.");
        }

        public static void UnregisterView(int viewIndex)
        {
            if ((uint)viewIndex < (uint)_views.Length) _views[viewIndex] = null;
        }

        // ── Registry accessors (for editor tooling) ───────────────────────────────────────

        public static MeshRegistry     Meshes    => _meshReg;
        public static MaterialRegistry Materials => _matReg;
        public static TextureCache     Textures  => _texCache;

        // ── Frame loop ───────────────────────────────────────────────────────────────────

        public static void BeginFrame()
        {
            if (!_initialized) return;
            _instanceBuf.BeginFrame();
            _lightBuf.Reset();
            _stats.Reset();
            _drawCount = 0;
            FrameProfiler.BeginFrame();
        }

        public static void RenderShadowMaps(in Matrix4x4 viewProj)
        {
            if (!_initialized) return;

            FrameProfiler.Begin(FrameProfiler.Zone.ShadowPass);
            CollectLightsAndShadows(ECSWorld.Instance, in viewProj, renderShadowPasses: true);
            FrameProfiler.End(FrameProfiler.Zone.ShadowPass);
        }

        public static void SubmitView(
            in Matrix4x4 viewProj,
            PipelineFlags basePipelineFlags = PipelineFlags.OffscreenRt,
            int viewIndex = 0,
            bool allowShadowPassRendering = true)
        {
            if (!_initialized) return;
            var world = ECSWorld.Instance;

            // Camera position is required for light importance ranking.
            Matrix4x4.Invert(viewProj, out var invVP);
            var cameraPos = new Vector3(invVP.M41, invVP.M42, invVP.M43);

            // ── 1. Collect lights and shadow matrices ───────────────────────────────────

            CollectLightsAndShadows(world, in viewProj, allowShadowPassRendering);

            // ── 2. Extract draw commands ──────────────────────────────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.EcsExtract);
            _drawCount = 0;
            for (int ei = 0; ei < world.Entities.Count; ei++)
            {
                if (_drawCount >= RenderingConstants.MAX_DRAWS) break;
                Entity id = world.Entities[ei];
                if (!world.TryGetComponent<ActiveFlag>(id, out var active) || !active.Active) continue;
                if (!world.TryGetComponent<MeshRenderer>(id, out var mr) || !mr.Visible) continue;
                if (!world.TryGetComponent<Transform>(id, out var tf)) continue;

                MeshResource? meshRes = _meshReg.GetByPath(mr.MeshPath);
                if (meshRes == null) continue;

                bool disableSubMeshMaterial = string.Equals(
                    mr.MaterialPath,
                    MeshRenderer.NoMaterialSentinel,
                    StringComparison.Ordinal);

                ushort matId;
                if (string.IsNullOrEmpty(mr.MaterialPath) || disableSubMeshMaterial)
                {
                    matId = 0;
                }
                else
                {
                    matId = _matReg.GetIdByKey(mr.MaterialPath);
                    if (matId == 0)
                        matId = _matReg.GetFirstIdByMtlFile(mr.MaterialPath);
                }
                ushort drawFlags = disableSubMeshMaterial ? DrawFlagDisableSubMeshMaterial : (ushort)0;

                Matrix4x4 model    = Transform.GetWorldMatrix(world, tf);
                Aabb worldAabb      = meshRes.LocalBounds.Transform(model);
                float worldRadius   = worldAabb.Extents.Length();
                float dist          = Vector3.Distance(cameraPos, worldAabb.Center);
                int lodIndex        = LodSelector.Pick(worldRadius, dist, 0);
                if (lodIndex == LodSelector.Skip) { _stats.Culled++; continue; }

                ushort lodMask = (ushort)(drawFlags | (ushort)lodIndex);
                _cmds[_drawCount]    = new DrawCommand(meshRes.Id, matId, lodMask, 0, 0u, worldAabb.Center, worldRadius);
                _cpuInst[_drawCount] = new InstanceData(
                    in model,
                    new Vector4(1f, 1f, 1f, mr.ReceivesShadows ? 1f : 0f));
                _drawCount++;
            }

            FrameProfiler.End(FrameProfiler.Zone.EcsExtract);
            if (_drawCount == 0) return;

            // ── 2b. Frustum cull (parallel on non-WASM) ───────────────────────────────────

            var frustum = Frustum.ExtractFromViewProj(in viewProj);
            FrameProfiler.Begin(FrameProfiler.Zone.ParallelCull);
            ParallelCuller.Run(in frustum, _cmds, _drawCount, _visible, out int visibleCount);
            FrameProfiler.End(FrameProfiler.Zone.ParallelCull);
            _stats.Culled += _drawCount - visibleCount;
            if (visibleCount == 0) return;

            // ── 3. Sort visible commands by (MaterialId | MeshId) ─────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.Sort);
            for (int j = 0; j < visibleCount; j++)
            {
                int idx = _visible[j];
                uint noMatBit = (_cmds[idx].LodMask & DrawFlagDisableSubMeshMaterial) != 0 ? 1u : 0u;
                _sortKeys[idx]  = (uint)(_cmds[idx].MaterialId << 17 | noMatBit << 16 | _cmds[idx].MeshId);
                _sortOrder[j] = idx;
            }
            Array.Sort(_sortOrder, 0, visibleCount, _drawSorter);
            FrameProfiler.End(FrameProfiler.Zone.Sort);

            // ── 4. Write instance data in sorted order; ONE sg_append_buffer per view ──────

            FrameProfiler.Begin(FrameProfiler.Zone.InstanceWrite);
            _instanceBuf.ResetStaging();
            int submitCount = visibleCount;
            for (int j = 0; j < visibleCount; j++)
            {
                if (!_instanceBuf.TryAppend(in _cpuInst[_sortOrder[j]]))
                {
#if DEBUG
                    _stats.InstancesDropped += visibleCount - j;
#endif
                    submitCount = j;  // clamp: group-walking loop must not exceed staged range
                    break;
                }
            }
            if (submitCount == 0) { FrameProfiler.End(FrameProfiler.Zone.InstanceWrite); return; }
            int instanceBaseByteOffset = _instanceBuf.Flush();
            _stats.InstancesSubmitted += submitCount;
            FrameProfiler.End(FrameProfiler.Zone.InstanceWrite);

            // ── 5. Camera position from inverse VP ────────────────────────────────────────

            var vsParams = new blinn_phong_vs_params_t
            {
                view_proj  = viewProj,
                camera_pos = new Vector4(cameraPos, 1f),
                dir_shadow_vp = _hasDirectionalShadow ? _directionalShadowViewProj : Matrix4x4.Identity,
            };

            // ── 6. Walk sorted groups ─────────────────────────────────────────────────────

            FrameProfiler.Begin(FrameProfiler.Zone.DrawCalls);
            int instanceOffset = 0;
            int i = 0;

            while (i < submitCount)
            {
                int firstIdx = _sortOrder[i];
                ushort curMat  = _cmds[firstIdx].MaterialId;
                ushort curMesh = _cmds[firstIdx].MeshId;
                  bool disableSubMeshMaterial = (_cmds[firstIdx].LodMask & DrawFlagDisableSubMeshMaterial) != 0;

                int groupSize = 0;
                while (i + groupSize < submitCount
                       && _cmds[_sortOrder[i + groupSize]].MaterialId == curMat
                      && _cmds[_sortOrder[i + groupSize]].MeshId     == curMesh
                      && ((_cmds[_sortOrder[i + groupSize]].LodMask & DrawFlagDisableSubMeshMaterial) != 0) == disableSubMeshMaterial)
                    groupSize++;

                Material?     mat  = _matReg.GetById(curMat);
                MeshResource? mesh = _meshReg.GetById(curMesh);

                if (mesh == null || mesh.SubMeshes == null || mesh.SubMeshes.Length == 0)
                {
                    instanceOffset += groupSize;
                    i += groupSize;
                    continue;
                }

                bool groupAlpha = mat is BlinnPhongMaterial bpmG && bpmG.HasAlpha;
                sg_apply_pipeline(_shaderCache.GetPipeline(
                    groupAlpha
                        ? basePipelineFlags | PipelineFlags.AlphaBlend
                        : basePipelineFlags));

                // Apply VS uniforms after pipeline (required by sokol validation).
                sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));

                int instByteOffset = instanceOffset * Unsafe.SizeOf<InstanceData>();

                foreach (MeshSubResource sub in mesh.SubMeshes)
                {
                    if (sub.IndexCount == 0 || sub.VertexBuffer.id == 0 || sub.IndexBuffer.id == 0)
                        continue;

                    // Per-sub-mesh material override (from .mtl material name).
                    BlinnPhongMaterial? bpm = ResolveSubMeshMaterial(mat, mesh, sub, disableSubMeshMaterial);
                    bool subAlpha = bpm?.HasAlpha ?? groupAlpha;

                    // If alpha state differs from group, re-apply pipeline then VS uniforms.
                    if (subAlpha != groupAlpha)
                    {
                        sg_apply_pipeline(_shaderCache.GetPipeline(
                            subAlpha
                                ? basePipelineFlags | PipelineFlags.AlphaBlend
                                : basePipelineFlags));
                        sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));
                    }

                    // Always apply FS uniforms per sub-mesh: each sub-mesh can have distinct
                    // Kd/Ks/Ns values from the .mtl file, independent of the group-level material.
                    BuildFsParams(bpm ?? mat, cameraPos, out var subFs);
                    sg_apply_uniforms(UB_blinn_phong_fs_params, SG_RANGE(ref subFs));

                    sg_view  diffuse  = bpm?.DiffuseMap  ?? _texCache.PlaceholderWhite;
                    sg_view  specular = bpm?.SpecularMap ?? _texCache.PlaceholderWhite;
                    sg_view  normal   = bpm?.NormalMap   ?? _texCache.PlaceholderNormal;
                    sg_view  opacity  = bpm?.OpacityMap  ?? _texCache.PlaceholderWhite;
                    sg_sampler smp    = (bpm?.Sampler.id ?? 0) != 0
                                        ? bpm!.Sampler
                                        : _texCache.DefaultSampler;

                    sg_apply_bindings(new sg_bindings
                    {
                        vertex_buffers        = { [0] = sub.VertexBuffer, [1] = _instanceBuf.Buffer },
                        vertex_buffer_offsets = { [1] = instanceBaseByteOffset + instByteOffset },
                        index_buffer          = sub.IndexBuffer,
                        views = {
                            [VIEW_diffuse_map]  = diffuse,
                            [VIEW_specular_map] = specular,
                            [VIEW_normal_map]   = normal,
                            [VIEW_opacity_map]  = opacity,
                            [VIEW_shadow_atlas] = _shadowAtlas.TextureView,
                            [VIEW_cube_shadow_array] = _cubeShadows.TextureView,
                        },
                        samplers = {
                            [SMP_diffuse_smp]  = smp,
                            [SMP_specular_smp] = smp,
                            [SMP_normal_smp]   = smp,
                            [SMP_opacity_smp]  = smp,
                            [SMP_shadow_atlas_smp] = _shadowSampler,
                            [SMP_cube_shadow_array_smp] = _cubeShadowSampler,
                        },
                    });

                    sg_draw(0u, (uint)sub.IndexCount, (uint)groupSize);
                    _stats.DrawCalls++;
                }

                instanceOffset += groupSize;
                i += groupSize;
            }
            FrameProfiler.End(FrameProfiler.Zone.DrawCalls);
        }

        public static void EndFrame() { FrameProfiler.EndFrame(); }

        /// <summary>
        /// Draws a shadow atlas debug overlay in the bottom-right corner.
        /// Must be called inside an active <c>sg_begin_pass / sg_end_pass</c>.
        /// </summary>
        public static void DrawShadowAtlasDebug(int rtWidth, int rtHeight)
        {
            if (!_initialized || !ShowShadowAtlasDebug) return;
            int size = System.Math.Min(rtWidth, rtHeight) / 4;
            int x    = rtWidth  - size - 8;
            int y    = rtHeight - size - 8;
            _shadowDebugPass.Draw(_shadowAtlas.TextureView,
                ShadowAtlasDebugSlice, x, y, size, rtWidth, rtHeight);
        }

        // ── Helpers ──────────────────────────────────────────────────────────────────────

        private static void CollectLightsAndShadows(ECSWorld world, in Matrix4x4 cameraViewProj, bool renderShadowPasses)
        {
            Matrix4x4.Invert(cameraViewProj, out var _invCamVP);
            Vector3 cameraPos = new Vector3(_invCamVP.M41, _invCamVP.M42, _invCamVP.M43);
            _lightBuf.Reset();
            _topLightCount = 0;
            _spotShadowTopCount = 0;
            _pointShadowTopCount = 0;
            _hasDirectionalShadow = false;
            _directionalShadowViewProj = Matrix4x4.Identity;
            for (int si = 0; si < _spotShadowViewProj.Length; si++)
                _spotShadowViewProj[si] = Matrix4x4.Identity;
            for (int pi = 0; pi < _pointShadowViewProj.Length; pi++)
                _pointShadowViewProj[pi] = Matrix4x4.Identity;

            Light bestDirectionalShadowLight = default;
            float bestDirectionalShadowScore = float.NegativeInfinity;
            bool hasDirectionalShadowLight = false;

            for (int li = 0; li < world.Entities.Count; li++)
            {
                Entity lid = world.Entities[li];
                if (!world.TryGetComponent<ActiveFlag>(lid, out var la) || !la.Active) continue;
                if (!world.TryGetComponent<LightComponent>(lid, out var lc)) continue;
                if (!lc.Enabled) continue;
                if (!world.TryGetComponent<Transform>(lid, out var lt)) continue;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, lt);
                var worldPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);
                var fwd = Vector3.Normalize(new Vector3(lightWorld.M31, lightWorld.M32, lightWorld.M33));

                float importance = MathF.Max(lc.Intensity, 0f);
                if (lc.Type != GameEditor.Framework.ECS.Components.LightType.Directional)
                {
                    float distSq = Vector3.DistanceSquared(cameraPos, worldPos);
                    importance *= 1f / MathF.Max(distSq, 0.01f);
                }

                float innerRad = lc.InnerAngle * (MathF.PI / 180f);
                float outerRad = lc.OuterAngle * (MathF.PI / 180f);

                var l = new Light(
                    (Lighting.LightType)(int)lc.Type,
                    worldPos,
                    fwd,
                    lc.Color,
                    lc.Intensity,
                    lc.Range,
                    innerRad,
                    outerRad
                );
                TryInsertTopLight(in l, importance);

                if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Directional && importance > bestDirectionalShadowScore)
                {
                    bestDirectionalShadowScore = importance;
                    bestDirectionalShadowLight = l;
                    hasDirectionalShadowLight = true;
                }

                if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Spot)
                {
                    TryInsertTopSpotShadowIndex(li, importance);
                }
                else if (lc.CastsShadows && lc.Type == GameEditor.Framework.ECS.Components.LightType.Point)
                {
                    TryInsertTopPointShadowIndex(li, importance);
                }
            }

            for (int li = 0; li < _topLightCount; li++)
            {
                if (hasDirectionalShadowLight && IsSameLight(in _topLights[li], in bestDirectionalShadowLight))
                {
                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        0);
                }
            }

            if (hasDirectionalShadowLight && TryComputeCasterBounds(world, out var casterMin, out var casterMax))
            {
                _directionalShadowViewProj = BuildDirectionalShadowViewProj(in bestDirectionalShadowLight, casterMin, casterMax);
                _hasDirectionalShadow = true;
                if (renderShadowPasses)
                    _shadowPass.RenderDirectional(world, _meshReg, _shadowAtlas, 0, in _directionalShadowViewProj);
            }

            for (int si = 0; si < _spotShadowTopCount; si++)
            {
                int lightEntityListIndex = _spotShadowTopIndices[si];
                Entity sid = world.Entities[lightEntityListIndex];
                if (!world.TryGetComponent<ActiveFlag>(sid, out var sa) || !sa.Active) continue;
                if (!world.TryGetComponent<LightComponent>(sid, out var slc) || slc.Type != GameEditor.Framework.ECS.Components.LightType.Spot || !slc.CastsShadows) continue;
                if (!world.TryGetComponent<Transform>(sid, out var slt)) continue;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, slt);
                var spotPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);
                var spotFwd = Vector3.Normalize(new Vector3(lightWorld.M31, lightWorld.M32, lightWorld.M33));
                float outerRad = slc.OuterAngle * (MathF.PI / 180f);

                Matrix4x4 spotVp = BuildSpotShadowViewProj(spotPos, spotFwd, slc.Range, outerRad);
                int atlasSlice = ShadowAtlas.DirectionalCascades + si;
                if (renderShadowPasses)
                    _shadowPass.RenderSpot(world, _meshReg, _shadowAtlas, atlasSlice, in spotVp);
                _spotShadowViewProj[si] = spotVp;

                for (int li = 0; li < _topLightCount; li++)
                {
                    if (_topLights[li].Type != Lighting.LightType.Spot) continue;
                    if (Vector3.DistanceSquared(_topLights[li].Position, spotPos) > 0.0001f) continue;

                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        atlasSlice);
                    break;
                }
            }

            for (int pi = 0; pi < _pointShadowTopCount; pi++)
            {
                int lightEntityListIndex = _pointShadowTopIndices[pi];
                Entity pid = world.Entities[lightEntityListIndex];
                if (!world.TryGetComponent<ActiveFlag>(pid, out var pa) || !pa.Active) continue;
                if (!world.TryGetComponent<LightComponent>(pid, out var plc) || plc.Type != GameEditor.Framework.ECS.Components.LightType.Point || !plc.CastsShadows) continue;
                if (!world.TryGetComponent<Transform>(pid, out var plt)) continue;

                Matrix4x4 lightWorld = Transform.GetWorldMatrix(world, plt);
                var pointPos = new Vector3(lightWorld.M41, lightWorld.M42, lightWorld.M43);

                for (int face = 0; face < CubeShadowArray.FacesPerLight; face++)
                {
                    Matrix4x4 pointFaceVp = BuildPointShadowFaceViewProj(pointPos, face, plc.Range);
                    if (renderShadowPasses)
                        _shadowPass.RenderPointFace(world, _meshReg, _cubeShadows, pi, face, in pointFaceVp);
                    _pointShadowViewProj[pi * CubeShadowArray.FacesPerLight + face] = pointFaceVp;
                }

                for (int li = 0; li < _topLightCount; li++)
                {
                    if (_topLights[li].Type != Lighting.LightType.Point) continue;
                    if (Vector3.DistanceSquared(_topLights[li].Position, pointPos) > 0.0001f) continue;

                    _topLights[li] = new Light(
                        _topLights[li].Type,
                        _topLights[li].Position,
                        _topLights[li].Direction,
                        _topLights[li].Color,
                        _topLights[li].Intensity,
                        _topLights[li].Range,
                        _topLights[li].InnerAngle,
                        _topLights[li].OuterAngle,
                        pi);
                    break;
                }
            }

            _lightBuf.Reset();
            for (int li = 0; li < _topLightCount; li++)
            {
                _lightBuf.Add(in _topLights[li]);
            }
        }

        private static void BuildFsParams(Material? mat, Vector3 cameraPos,
                                          out blinn_phong_fs_params_t fs)
        {
            fs = new blinn_phong_fs_params_t();

            if (mat is BlinnPhongMaterial bpm)
            {
                fs.material_kd_alpha = new Vector4(bpm.DiffuseColor,  bpm.Opacity);
                fs.material_ks_shin  = new Vector4(bpm.SpecularColor, bpm.Shininess);
            }
            else
            {
                fs.material_kd_alpha = Vector4.One;
                fs.material_ks_shin  = new Vector4(0f, 0f, 0f, 1f);
            }

            fs.ambient_num = new Vector4(0.1f, 0.1f, 0.1f, _lightBuf.Count);
            fs.cam_pos_pad = new Vector4(cameraPos, (float)ShadowQuality);

            int n      = _lightBuf.Count;
            var lights = _lightBuf.ActiveSpan;
            for (int l = 0; l < n; l++)
            {
                int b = l * 4;
                fs.lights_data[b + 0] = lights[l].PositionType;
                fs.lights_data[b + 1] = lights[l].DirectionRange;
                fs.lights_data[b + 2] = lights[l].ColorIntensity;
                fs.lights_data[b + 3] = lights[l].SpotShadow;
            }

            for (int si = 0; si < ShadowAtlas.SpotSlices; si++)
            {
                int b = si * 4;
                var m = _spotShadowViewProj[si];
                fs.spot_shadow_vp[b + 0] = new Vector4(m.M11, m.M12, m.M13, m.M14);
                fs.spot_shadow_vp[b + 1] = new Vector4(m.M21, m.M22, m.M23, m.M24);
                fs.spot_shadow_vp[b + 2] = new Vector4(m.M31, m.M32, m.M33, m.M34);
                fs.spot_shadow_vp[b + 3] = new Vector4(m.M41, m.M42, m.M43, m.M44);
            }

            for (int pi = 0; pi < _pointShadowViewProj.Length; pi++)
            {
                int b = pi * 4;
                var m = _pointShadowViewProj[pi];
                fs.point_shadow_vp[b + 0] = new Vector4(m.M11, m.M12, m.M13, m.M14);
                fs.point_shadow_vp[b + 1] = new Vector4(m.M21, m.M22, m.M23, m.M24);
                fs.point_shadow_vp[b + 2] = new Vector4(m.M31, m.M32, m.M33, m.M34);
                fs.point_shadow_vp[b + 3] = new Vector4(m.M41, m.M42, m.M43, m.M44);
            }
        }

        private static BlinnPhongMaterial? ResolveSubMeshMaterial(
            Material? entityMat, MeshResource mesh, MeshSubResource sub, bool disableSubMeshMaterial)
        {
            if (!disableSubMeshMaterial
                && sub.MaterialKey.Length > 0
                && _matReg.GetByKey(sub.MaterialKey) is BlinnPhongMaterial subBpm)
                return subBpm;
            return entityMat as BlinnPhongMaterial;
        }

        private static Matrix4x4 BuildDirectionalShadowViewProj(in Light light, Vector3 casterMin, Vector3 casterMax)
        {
            const float DepthExtension = 50f; // extra depth behind casters so receivers (e.g. the floor) stay in range
            const float Pad            = 2f;  // world-space margin so grazing-angle shadows aren't clipped

            Vector3 toLight = Vector3.Normalize(-light.Direction);
            Vector3 up = Vector3.UnitY;
            if (MathF.Abs(Vector3.Dot(up, toLight)) > 0.98f)
                up = Vector3.UnitZ;

            // Fit the ortho frustum tightly to the shadow-casting geometry rather than the
            // camera frustum. The camera frustum can be 100+ units across, which wastes
            // almost the entire 2048² atlas slice on empty space and leaves the actual
            // casters only a few dozen texels (pixelated shadows that PCF then smears).
            // A bounding *sphere* keeps the box size constant as casters rotate, so the
            // texel-snap below can remove shadow-edge crawl. This is also inherently
            // camera-independent, so shadows never vanish as the camera pulls away.
            Vector3 center = (casterMin + casterMax) * 0.5f;
            float radius   = MathF.Max((casterMax - casterMin).Length() * 0.5f, 0.1f);
            float boxHalf  = radius + Pad;

            Vector3 lightEye = center + toLight * (radius + DepthExtension);
            Matrix4x4 lightView = Matrix4x4.CreateLookAt(lightEye, center, up);

            Vector3 centerLS = Vector3.Transform(center, lightView);

            float minX = centerLS.X - boxHalf;
            float minY = centerLS.Y - boxHalf;

            // Texel-snap the box origin in light space so edges don't crawl when casters move.
            float worldPerTexel = (2f * boxHalf) / ShadowAtlas.SliceSize;
            minX = MathF.Floor(minX / worldPerTexel) * worldPerTexel;
            minY = MathF.Floor(minY / worldPerTexel) * worldPerTexel;
            float maxX = minX + 2f * boxHalf;
            float maxY = minY + 2f * boxHalf;

            // Right-handed light view: casters lie in front of the eye at negative Z.
            float centerDepth = -centerLS.Z;
            float near = MathF.Max(0.05f, centerDepth - radius - Pad);
            float far  = centerDepth + radius + DepthExtension;

            Matrix4x4 proj = Matrix4x4.CreateOrthographicOffCenter(minX, maxX, minY, maxY, near, far);
            return lightView * proj;
        }

        /// <summary>
        /// World-space AABB of all active, visible, shadow-casting meshes.
        /// Returns false when the scene has no casters (directional shadows are then skipped).
        /// </summary>
        private static bool TryComputeCasterBounds(ECSWorld world, out Vector3 min, out Vector3 max)
        {
            min = new Vector3(float.MaxValue);
            max = new Vector3(float.MinValue);
            bool any = false;

            for (int i = 0; i < world.Entities.Count; i++)
            {
                Entity id = world.Entities[i];
                if (!world.TryGetComponent<ActiveFlag>(id, out var active) || !active.Active) continue;
                if (!world.TryGetComponent<MeshRenderer>(id, out var mr) || !mr.Visible || !mr.CastsShadows) continue;
                if (!world.TryGetComponent<Transform>(id, out var tf)) continue;

                MeshResource? mesh = _meshReg.GetByPath(mr.MeshPath);
                if (mesh == null) continue;

                Aabb worldBounds = mesh.LocalBounds.Transform(Transform.GetWorldMatrix(world, tf));
                min = Vector3.Min(min, worldBounds.Min);
                max = Vector3.Max(max, worldBounds.Max);
                any = true;
            }

            return any;
        }

        private static Matrix4x4 BuildSpotShadowViewProj(Vector3 position, Vector3 direction, float range, float outerAngleRad)
        {
            Vector3 target = position + direction;
            Vector3 up = Vector3.UnitY;
            if (MathF.Abs(Vector3.Dot(up, direction)) > 0.98f)
                up = Vector3.UnitZ;

            float fov = MathF.Max(outerAngleRad * 2f, 0.1f);
            float farPlane  = MathF.Max(range, 0.1f);
            // Perspective shadow depth is highly non-linear: a tiny near plane pushes
            // nearly the whole [0,1] depth range into the first few percent of distance,
            // which inflates the effective world-space depth bias near the far plane and
            // makes short occluders (e.g. a cube on the floor) stop casting shadows.
            // Keep the near plane as large as the range allows to preserve precision.
            // (Orthographic directional shadows have linear depth and don't need this.)
            float nearPlane = MathF.Max(0.5f, farPlane * 0.1f);
            Matrix4x4 view = Matrix4x4.CreateLookAt(position, target, up);
            Matrix4x4 proj = Matrix4x4.CreatePerspectiveFieldOfView(fov, 1f, nearPlane, farPlane);
            return view * proj;
        }

        private static Matrix4x4 BuildPointShadowFaceViewProj(Vector3 position, int faceIndex, float range)
        {
            Vector3 dir;
            Vector3 up;
            switch (faceIndex)
            {
                case 0: dir = Vector3.UnitX; up = -Vector3.UnitY; break;
                case 1: dir = -Vector3.UnitX; up = -Vector3.UnitY; break;
                case 2: dir = Vector3.UnitY; up = Vector3.UnitZ; break;
                case 3: dir = -Vector3.UnitY; up = -Vector3.UnitZ; break;
                case 4: dir = Vector3.UnitZ; up = -Vector3.UnitY; break;
                default: dir = -Vector3.UnitZ; up = -Vector3.UnitY; break;
            }

            // See BuildSpotShadowViewProj: a larger near plane preserves perspective
            // depth precision so the constant shader bias stays small in world space.
            float farPlane  = MathF.Max(range, 0.1f);
            float nearPlane = MathF.Max(0.5f, farPlane * 0.1f);
            Matrix4x4 view = Matrix4x4.CreateLookAt(position, position + dir, up);
            Matrix4x4 proj = Matrix4x4.CreatePerspectiveFieldOfView(MathF.PI * 0.5f, 1f, nearPlane, farPlane);
            return view * proj;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopLight(in Light light, float score)
        {
            if (_topLightCount < RenderingConstants.MAX_LIGHTS)
            {
                int insert = _topLightCount;
                while (insert > 0 && score > _topLightScores[insert - 1]) insert--;
                for (int i = _topLightCount; i > insert; i--)
                {
                    _topLights[i] = _topLights[i - 1];
                    _topLightScores[i] = _topLightScores[i - 1];
                }
                _topLights[insert] = light;
                _topLightScores[insert] = score;
                _topLightCount++;
                return;
            }

            // Already full: drop low-priority light immediately.
            if (score <= _topLightScores[RenderingConstants.MAX_LIGHTS - 1]) return;

            int at = RenderingConstants.MAX_LIGHTS - 1;
            while (at > 0 && score > _topLightScores[at - 1]) at--;
            for (int i = RenderingConstants.MAX_LIGHTS - 1; i > at; i--)
            {
                _topLights[i] = _topLights[i - 1];
                _topLightScores[i] = _topLightScores[i - 1];
            }
            _topLights[at] = light;
            _topLightScores[at] = score;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool IsSameLight(in Light a, in Light b)
        {
            return a.Type == b.Type
                && a.Position == b.Position
                && a.Direction == b.Direction
                && a.Color == b.Color
                && a.Intensity == b.Intensity
                && a.Range == b.Range
                && a.InnerAngle == b.InnerAngle
                && a.OuterAngle == b.OuterAngle;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopSpotShadowIndex(int entityListIndex, float score)
        {
            if (_spotShadowTopCount < ShadowAtlas.SpotSlices)
            {
                int insert = _spotShadowTopCount;
                while (insert > 0 && score > _spotShadowTopScores[insert - 1])
                {
                    _spotShadowTopIndices[insert] = _spotShadowTopIndices[insert - 1];
                    _spotShadowTopScores[insert] = _spotShadowTopScores[insert - 1];
                    insert--;
                }
                _spotShadowTopIndices[insert] = entityListIndex;
                _spotShadowTopScores[insert] = score;
                _spotShadowTopCount++;
                return;
            }

            if (score <= _spotShadowTopScores[ShadowAtlas.SpotSlices - 1]) return;

            int at = ShadowAtlas.SpotSlices - 1;
            while (at > 0 && score > _spotShadowTopScores[at - 1])
            {
                _spotShadowTopIndices[at] = _spotShadowTopIndices[at - 1];
                _spotShadowTopScores[at] = _spotShadowTopScores[at - 1];
                at--;
            }
            _spotShadowTopIndices[at] = entityListIndex;
            _spotShadowTopScores[at] = score;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void TryInsertTopPointShadowIndex(int entityListIndex, float score)
        {
            if (_pointShadowTopCount < CubeShadowArray.MaxPointShadowLights)
            {
                int insert = _pointShadowTopCount;
                while (insert > 0 && score > _pointShadowTopScores[insert - 1])
                {
                    _pointShadowTopIndices[insert] = _pointShadowTopIndices[insert - 1];
                    _pointShadowTopScores[insert] = _pointShadowTopScores[insert - 1];
                    insert--;
                }
                _pointShadowTopIndices[insert] = entityListIndex;
                _pointShadowTopScores[insert] = score;
                _pointShadowTopCount++;
                return;
            }

            if (score <= _pointShadowTopScores[CubeShadowArray.MaxPointShadowLights - 1]) return;

            int at = CubeShadowArray.MaxPointShadowLights - 1;
            while (at > 0 && score > _pointShadowTopScores[at - 1])
            {
                _pointShadowTopIndices[at] = _pointShadowTopIndices[at - 1];
                _pointShadowTopScores[at] = _pointShadowTopScores[at - 1];
                at--;
            }
            _pointShadowTopIndices[at] = entityListIndex;
            _pointShadowTopScores[at] = score;
        }

        private sealed class DrawSorter : System.Collections.Generic.IComparer<int>
        {
            public int Compare(int x, int y) => _sortKeys[x].CompareTo(_sortKeys[y]);
        }
    }
}
