// RenderingServer.cs — M1 implementation of the rendering server.
//
// Depends on blinn_phong_shader_cs.Shaders (generated by sokol-shdc from
// src/Framework/Renderer/Server/shaders/blinn_phong.glsl). The compiled output
// (blinn_phong_shader.cs) lives in the same shaders/ folder and is built by
// the CompileFrameworkShaders MSBuild target in Framework.csproj.
//
// Frame loop:
//   BeginFrame()  → reset instance staging count, reset light buffer, reset stats
//   SubmitView()  → Extract ECS → Sort → Append instances (sg_append_buffer per view) → Draw groups
//   EndFrame()    → (reserved for future stats push)
// Note: sg_append_buffer (not sg_update_buffer) is required so two views in the same
//       Sokol frame can each append without clobbering one another.

using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using Frent;
using Sokol;
using static Sokol.SG;
using static Sokol.Utils;
using static blinn_phong_shader_cs.Shaders;
using GameEditor.Framework.Core;
using GameEditor.Framework.ECS;
using GameEditor.Framework.ECS.Components;
using GameEditor.Framework.Renderer.Server.Lighting;
using GameEditor.Framework.Renderer.Server.Materials;
using GameEditor.Framework.Renderer.Server.Resources;

namespace GameEditor.Framework.Renderer.Server
{
    public static unsafe class RenderingServer
    {
        // ── Sub-systems ──────────────────────────────────────────────────────────────────

        private static readonly TextureCache       _texCache    = new();
        private static readonly MeshRegistry       _meshReg     = new();
        private static readonly MaterialRegistry   _matReg      = new(_texCache);
        private static readonly LightBuffer        _lightBuf    = new();
        private static readonly InstanceBuffer     _instanceBuf = new();
        private static readonly ShaderVariantCache _shaderCache = new();
        private static readonly RenderView?[]      _views       = new RenderView[RenderingConstants.MAX_VIEWS];

        // ── Per-frame scratch (pre-allocated – zero hot-path allocations) ────────────────

        private static readonly DrawCommand[]  _cmds      = new DrawCommand[RenderingConstants.MAX_DRAWS];
        private static readonly InstanceData[] _cpuInst   = new InstanceData[RenderingConstants.MAX_DRAWS];
        private static int _drawCount;

        private static readonly uint[]     _sortKeys   = new uint[RenderingConstants.MAX_DRAWS];
        private static readonly int[]      _sortOrder  = new int[RenderingConstants.MAX_DRAWS];
        private static readonly DrawSorter _drawSorter = new();

        // ── Frame stats ──────────────────────────────────────────────────────────────────

        private static FrameStats _stats;
        public static ref readonly FrameStats Stats => ref _stats;

        private static bool _initialized;

        // ── Lifecycle ────────────────────────────────────────────────────────────────────

        public static void Init()
        {
            if (_initialized) return;
            _texCache.Init();
            _shaderCache.Init();
            _initialized = true;
        }

        public static void Shutdown()
        {
            if (!_initialized) return;
            _initialized = false;
            _instanceBuf.Dispose();
            _matReg.Shutdown();
            _meshReg.Shutdown();
            _texCache.Shutdown();
            _shaderCache.Dispose();
        }

        // ── View management ──────────────────────────────────────────────────────────────

        public static int RegisterView(RenderView view)
        {
            for (int i = 0; i < _views.Length; i++)
                if (_views[i] == null) { _views[i] = view; return i; }
            throw new InvalidOperationException("Maximum views exceeded.");
        }

        public static void UnregisterView(int viewIndex)
        {
            if ((uint)viewIndex < (uint)_views.Length) _views[viewIndex] = null;
        }

        // ── Registry accessors (for editor tooling) ───────────────────────────────────────

        public static MeshRegistry     Meshes    => _meshReg;
        public static MaterialRegistry Materials => _matReg;
        public static TextureCache     Textures  => _texCache;

        // ── Frame loop ───────────────────────────────────────────────────────────────────

        public static void BeginFrame()
        {
            if (!_initialized) return;
            _instanceBuf.BeginFrame();
            _lightBuf.Reset();
            _stats.Reset();
            _drawCount = 0;
        }

        public static void SubmitView(in Matrix4x4 viewProj, PipelineFlags basePipelineFlags = PipelineFlags.OffscreenRt, int viewIndex = 0)
        {
            if (!_initialized) return;
            var world = ECSWorld.Instance;

            // ── 1. Collect lights ─────────────────────────────────────────────────────────

            _lightBuf.Reset();
            for (int li = 0; li < world.Entities.Count; li++)
            {
                if (_lightBuf.Count >= RenderingConstants.MAX_LIGHTS) break;
                Entity lid = world.Entities[li];
                if (!world.TryGetComponent<ActiveFlag>(lid, out var la) || !la.Active) continue;
                if (!world.TryGetComponent<LightComponent>(lid, out var lc)) continue;
                if (!world.TryGetComponent<Transform>(lid, out var lt)) continue;

                var rot = Matrix4x4.CreateFromQuaternion(lt.Rotation);
                var fwd = new Vector3(rot.M31, rot.M32, rot.M33);

                var l = new Light(
                    (Lighting.LightType)(int)lc.Type,
                    lt.Position,
                    fwd,
                    lc.Color,
                    lc.Intensity,
                    lc.Range,
                    lc.InnerAngle,
                    lc.OuterAngle
                );
                _lightBuf.Add(in l);
            }

            // ── 2. Extract draw commands ──────────────────────────────────────────────────

            _drawCount = 0;
            for (int ei = 0; ei < world.Entities.Count; ei++)
            {
                if (_drawCount >= RenderingConstants.MAX_DRAWS) break;
                Entity id = world.Entities[ei];
                if (!world.TryGetComponent<ActiveFlag>(id, out var active) || !active.Active) continue;
                if (!world.TryGetComponent<MeshRenderer>(id, out var mr) || !mr.Visible) continue;
                if (!world.TryGetComponent<Transform>(id, out var tf)) continue;

                // Primitive-spec meshes are handled by SceneRenderer — skip them here.
                if (mr.MeshPath.StartsWith("prim:", StringComparison.Ordinal)) continue;

                MeshResource? meshRes = _meshReg.GetByPath(mr.MeshPath);
                if (meshRes == null) continue;

                ushort matId = string.IsNullOrEmpty(mr.MaterialPath)
                    ? (ushort)0
                    : _matReg.GetIdByKey(mr.MaterialPath);

                Matrix4x4 model = Transform.GetWorldMatrix(world, tf);

                _cmds[_drawCount]    = new DrawCommand(meshRes.Id, matId, 0, 0, 0u, tf.Position, 1f);
                _cpuInst[_drawCount] = new InstanceData(in model, Vector4.One);
                _drawCount++;
            }

            if (_drawCount == 0) return;

            // ── 3. Sort by (MaterialId << 16 | MeshId) ───────────────────────────────────

            for (int j = 0; j < _drawCount; j++)
            {
                _sortKeys[j]  = (uint)(_cmds[j].MaterialId << 16 | _cmds[j].MeshId);
                _sortOrder[j] = j;
            }
            Array.Sort(_sortOrder, 0, _drawCount, _drawSorter);

            // ── 4. Write instance data in sorted order; ONE sg_append_buffer per view ──────

            _instanceBuf.ResetStaging();
            for (int j = 0; j < _drawCount; j++)
            {
                if (!_instanceBuf.TryAppend(in _cpuInst[_sortOrder[j]]))
                {
#if DEBUG
                    _stats.InstancesDropped += _drawCount - j;
#endif
                    _drawCount = j;  // clamp: group-walking loop must not exceed staged range
                    break;
                }
            }
            if (_drawCount == 0) return;
            int instanceBaseByteOffset = _instanceBuf.Flush();
            _stats.InstancesSubmitted += _drawCount;

            // ── 5. Camera position from inverse VP ────────────────────────────────────────

            Matrix4x4.Invert(viewProj, out var invVP);
            var cameraPos = new Vector3(invVP.M41, invVP.M42, invVP.M43);

            var vsParams = new blinn_phong_vs_params_t
            {
                view_proj  = viewProj,
                camera_pos = new Vector4(cameraPos, 1f),
            };

            // ── 6. Walk sorted groups ─────────────────────────────────────────────────────

            int instanceOffset = 0;
            int i = 0;

            while (i < _drawCount)
            {
                int firstIdx = _sortOrder[i];
                ushort curMat  = _cmds[firstIdx].MaterialId;
                ushort curMesh = _cmds[firstIdx].MeshId;

                int groupSize = 0;
                while (i + groupSize < _drawCount
                       && _cmds[_sortOrder[i + groupSize]].MaterialId == curMat
                       && _cmds[_sortOrder[i + groupSize]].MeshId     == curMesh)
                    groupSize++;

                Material?     mat  = _matReg.GetById(curMat);
                MeshResource? mesh = _meshReg.GetById(curMesh);

                if (mesh == null || mesh.SubMeshes == null || mesh.SubMeshes.Length == 0)
                {
                    instanceOffset += groupSize;
                    i += groupSize;
                    continue;
                }

                bool groupAlpha = mat is BlinnPhongMaterial bpmG && bpmG.HasAlpha;
                sg_apply_pipeline(_shaderCache.GetPipeline(
                    groupAlpha
                        ? basePipelineFlags | PipelineFlags.AlphaBlend
                        : basePipelineFlags));

                // Apply VS uniforms after pipeline (required by sokol validation).
                sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));

                int instByteOffset = instanceOffset * Unsafe.SizeOf<InstanceData>();

                foreach (MeshSubResource sub in mesh.SubMeshes)
                {
                    if (sub.IndexCount == 0 || sub.VertexBuffer.id == 0 || sub.IndexBuffer.id == 0)
                        continue;

                    // Per-sub-mesh material override (from .mtl material name).
                    BlinnPhongMaterial? bpm = ResolveSubMeshMaterial(mat, mesh, sub);
                    bool subAlpha = bpm?.HasAlpha ?? groupAlpha;

                    // If alpha state differs from group, re-apply pipeline then VS uniforms.
                    if (subAlpha != groupAlpha)
                    {
                        sg_apply_pipeline(_shaderCache.GetPipeline(
                            subAlpha
                                ? basePipelineFlags | PipelineFlags.AlphaBlend
                                : basePipelineFlags));
                        sg_apply_uniforms(UB_blinn_phong_vs_params, SG_RANGE(ref vsParams));
                    }

                    // Always apply FS uniforms per sub-mesh: each sub-mesh can have distinct
                    // Kd/Ks/Ns values from the .mtl file, independent of the group-level material.
                    BuildFsParams(bpm ?? mat, cameraPos, out var subFs);
                    sg_apply_uniforms(UB_blinn_phong_fs_params, SG_RANGE(ref subFs));

                    sg_view  diffuse  = bpm?.DiffuseMap  ?? _texCache.PlaceholderWhite;
                    sg_view  specular = bpm?.SpecularMap ?? _texCache.PlaceholderWhite;
                    sg_view  normal   = bpm?.NormalMap   ?? _texCache.PlaceholderNormal;
                    sg_view  opacity  = bpm?.OpacityMap  ?? _texCache.PlaceholderWhite;
                    sg_sampler smp    = (bpm?.Sampler.id ?? 0) != 0
                                        ? bpm!.Sampler
                                        : _texCache.DefaultSampler;

                    sg_apply_bindings(new sg_bindings
                    {
                        vertex_buffers        = { [0] = sub.VertexBuffer, [1] = _instanceBuf.Buffer },
                        vertex_buffer_offsets = { [1] = instanceBaseByteOffset + instByteOffset },
                        index_buffer          = sub.IndexBuffer,
                        views = {
                            [VIEW_diffuse_map]  = diffuse,
                            [VIEW_specular_map] = specular,
                            [VIEW_normal_map]   = normal,
                            [VIEW_opacity_map]  = opacity,
                        },
                        samplers = {
                            [SMP_diffuse_smp]  = smp,
                            [SMP_specular_smp] = smp,
                            [SMP_normal_smp]   = smp,
                            [SMP_opacity_smp]  = smp,
                        },
                    });

                    sg_draw(0u, (uint)sub.IndexCount, (uint)groupSize);
                    _stats.DrawCalls++;
                }

                instanceOffset += groupSize;
                i += groupSize;
            }
        }

        public static void EndFrame() { }

        // ── Helpers ──────────────────────────────────────────────────────────────────────

        private static void BuildFsParams(Material? mat, Vector3 cameraPos,
                                          out blinn_phong_fs_params_t fs)
        {
            fs = new blinn_phong_fs_params_t();

            if (mat is BlinnPhongMaterial bpm)
            {
                fs.material_kd_alpha = new Vector4(bpm.DiffuseColor,  bpm.Opacity);
                fs.material_ks_shin  = new Vector4(bpm.SpecularColor, bpm.Shininess);
            }
            else
            {
                fs.material_kd_alpha = Vector4.One;
                fs.material_ks_shin  = new Vector4(0f, 0f, 0f, 1f);
            }

            fs.ambient_num = new Vector4(0.1f, 0.1f, 0.1f, _lightBuf.Count);
            fs.cam_pos_pad = new Vector4(cameraPos, 0f);

            int n      = _lightBuf.Count;
            var lights = _lightBuf.ActiveSpan;
            for (int l = 0; l < n; l++)
            {
                int b = l * 4;
                fs.lights_data[b + 0] = lights[l].PositionType;
                fs.lights_data[b + 1] = lights[l].DirectionRange;
                fs.lights_data[b + 2] = lights[l].ColorIntensity;
                fs.lights_data[b + 3] = lights[l].SpotShadow;
            }
        }

        private static BlinnPhongMaterial? ResolveSubMeshMaterial(
            Material? entityMat, MeshResource mesh, MeshSubResource sub)
        {
            if (sub.MaterialKey.Length > 0 && _matReg.GetByKey(sub.MaterialKey) is BlinnPhongMaterial subBpm)
                return subBpm;
            return entityMat as BlinnPhongMaterial;
        }

        private sealed class DrawSorter : System.Collections.Generic.IComparer<int>
        {
            public int Compare(int x, int y) => _sortKeys[x].CompareTo(_sortKeys[y]);
        }
    }
}
