#!/usr/bin/env python3
"""Bake Sokol.Render2D's built-in particle sprites into a source file.

Render2D is consumed by *source-globbing* `src/Render2D/**/*.cs` (see docs/RENDER2D.md), not by
referencing a built DLL — so an `<EmbeddedResource>` in Render2D.csproj would never reach a consumer's
assembly. Instead we bake the sprite bytes (base64) straight into a `.cs` file that the same glob picks
up, so the textures compile into any consumer on every platform (NativeAOT/WASM) with zero asset-folder
copying and no per-platform bundling.

Run from anywhere; regenerates src/Render2D/Render2DEmbeddedAssets.cs from src/Render2D/Assets/particles/.
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "src", "Render2D", "Assets", "particles")
OUT = os.path.join(ROOT, "src", "Render2D", "Render2DEmbeddedAssets.cs")

# key (the logical path the presets use)  ->  (source filename, C# const name)
ASSETS = [
    ("particles/smoke.png",       "smoke.png",       "SmokePng"),
    ("particles/flame.svg",       "flame.svg",       "FlameSvg"),
    ("particles/blast_sheet.png", "blast_sheet.png", "BlastSheetPng"),
]

CHUNK = 120  # base64 chars per source line (adjacent string literals fold at compile time, no runtime cost)


def emit_const(name: str, b64: str) -> str:
    lines = [b64[i:i + CHUNK] for i in range(0, len(b64), CHUNK)]
    body = "\n        + ".join(f'"{ln}"' for ln in lines)
    return f"    const string {name} =\n          {body};\n"


def main():
    consts = []
    table = []
    for key, fname, const in ASSETS:
        with open(os.path.join(SRC_DIR, fname), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        consts.append(emit_const(const, b64))
        table.append(f'        ["{key}"] = {const},')

    out = (
        "// <auto-generated> Regenerate with scripts/gen-render2d-assets.py — do not edit by hand. </auto-generated>\n"
        "using System;\n"
        "using System.Collections.Generic;\n\n"
        "namespace Sokol.Render2D;\n\n"
        "/// <summary>The built-in particle sprites, baked into source as base64 so they compile straight\n"
        "/// into any consumer's assembly (consumers source-glob <c>src/Render2D/**</c>, see\n"
        "/// docs/RENDER2D.md) — no asset folder to copy, no per-platform bundling, works on every target\n"
        "/// under NativeAOT/WASM. Keyed by the same logical path the presets use (e.g.\n"
        "/// <c>\"particles/smoke.png\"</c>). Canonical source files live in src/Render2D/Assets/particles/.</summary>\n"
        "public static class Render2DEmbeddedAssets\n"
        "{\n"
        "    /// <summary>Built-in sprite bytes for <paramref name=\"key\"/>; false when the framework does not\n"
        "    /// ship that key (i.e. an app-supplied path, which the texture caches then load from the filesystem).</summary>\n"
        "    public static bool TryGet(string key, out byte[] bytes)\n"
        "    {\n"
        "        if (_b64.TryGetValue(key, out var s)) { bytes = Convert.FromBase64String(s); return true; }\n"
        "        bytes = Array.Empty<byte>();\n"
        "        return false;\n"
        "    }\n\n"
        "    static readonly Dictionary<string, string> _b64 = new()\n"
        "    {\n"
        + "\n".join(table) + "\n"
        "    };\n\n"
        + "\n".join(consts) +
        "}\n"
    )
    with open(OUT, "w") as f:
        f.write(out)
    print(f"wrote {OUT} ({len(out)} chars)")


if __name__ == "__main__":
    main()
